- resolwe_bio/processes/transmart/import.yml
- resolwe_bio/tests/test_transmart.py
- resolwe_bio/tools/curlprogress.py
- resolwe_bio/tools/transmart_fetch.R
- resolwe_bio/tools/transmart_import.py
- resolwe_bio/tools/transmart_utils.py
- resolwe_bio/tools/utils.py
The progress from cURL download from the tranSMART instance does not work yet. I suggest we accept this PR as is and add this feature later.
> Fix annotation data type and some bordering cases

- resolwe_bio/api/views.py
- tests/fixtures/collection.yaml
- tests/fixtures/data.yaml
Added test fixtures for sample data.
> Added test fixtures

- resolwe_bio/api/views.py
> Change sample viewset to filter based on query params

- .gitignore
- .travis.yml
- README.rst
- docs/CHANGELOG.rst
- docs/contributing.rst
- resolwe_bio/tests/test_alignment.py
- resolwe_bio/tests/test_annotation.py
- resolwe_bio/tests/test_assembler.py
- resolwe_bio/tests/test_chipseq.py
- resolwe_bio/tests/test_clustering.py
- resolwe_bio/tests/test_diff_expression.py
- resolwe_bio/tests/test_enrichment.py
- resolwe_bio/tests/test_expression.py
- resolwe_bio/tests/test_gencover.py
- resolwe_bio/tests/test_geneinfo.py
- resolwe_bio/tests/test_genome_coverage.py
- resolwe_bio/tests/test_jbrowse.py
- resolwe_bio/tests/test_pca.py
- resolwe_bio/tests/test_processor.py
- resolwe_bio/tests/test_pseudoalignment.py
- resolwe_bio/tests/test_reads_filtering.py
- resolwe_bio/tests/test_support_processors.py
- resolwe_bio/tests/test_upload.py
- resolwe_bio/tests/test_variant_calling.py
- resolwe_bio/tools/demultiplex.py
- setup.py
- tox.ini
Decorate all tests that currently fail on Docker with `skipDockerFailure`
> Use Travis CI to run the tests

- resolwe_bio/filters.py
- resolwe_bio/views.py
Requires https://github.com/genialis/resolwe/pull/71
> Move SampleFilter to separate file and update it

- resolwe_bio/management/commands/generate_samples.py
Changed argument names due to different terminology (samples/presamples) and did some cosmetic fixes.
Sample generation command now works, but I'm not sure if everything is ok, because I'm not familiar which fields have been added/updated. Maybe @mstajdohar should do a review pass.
> Update samples generation

- docs/CHANGELOG.rst
- resolwe_bio/tests/processes/test_alignment.py
- resolwe_bio/tests/processes/test_annotation.py
- resolwe_bio/tests/processes/test_assembler.py
- resolwe_bio/tests/processes/test_chipseq.py
- resolwe_bio/tests/processes/test_clustering.py
- resolwe_bio/tests/processes/test_demultiplex.py
- resolwe_bio/tests/processes/test_diff_expression.py
- resolwe_bio/tests/processes/test_enrichment.py
- resolwe_bio/tests/processes/test_expression.py
- resolwe_bio/tests/processes/test_gencover.py
- resolwe_bio/tests/processes/test_geneinfo.py
- resolwe_bio/tests/processes/test_genome_coverage.py
- resolwe_bio/tests/processes/test_jbrowse.py
- resolwe_bio/tests/processes/test_microarray.py
- resolwe_bio/tests/processes/test_pca.py
- resolwe_bio/tests/processes/test_processor.py
- resolwe_bio/tests/processes/test_pseudoalignment.py
- resolwe_bio/tests/processes/test_reads_filtering.py
- resolwe_bio/tests/processes/test_reads_manipulation.py
- resolwe_bio/tests/processes/test_support_processors.py
- resolwe_bio/tests/processes/test_transmart.py
- resolwe_bio/tests/processes/test_upload.py
- resolwe_bio/tests/processes/test_variant_calling.py
- resolwe_bio/tests/unit/test_generate_samples.py
- resolwe_bio/utils/__init__.py
- resolwe_bio/utils/test.py
> Improve test utilities packaging and update for the latest Resolwe

- resolwe_bio/views.py
Needed after genialis/resolwe#120
> Add contributor to prefetch_related

- docs/catalog.rst
- docs/conf.py
- docs/index.rst
No more corrections anticipated.
> Sphinx autoprocess extension

- docs/CHANGELOG.rst
- resolwe_bio/processes/import_data/expressions.yml
- resolwe_bio/tools/expression2storage.py
@jkokosar could you please review this. I rebased my commit on #99 as suggested.
> Save expressions from JSON file to Storage

- docs/CHANGELOG.rst
- resolwe_bio/management/commands/generate_diffexpr_cuffdiff.py
- resolwe_bio/management/commands/generate_diffexpr_deseq.py
- resolwe_bio/management/commands/generate_geneset.py
- resolwe_bio/management/commands/generate_samples.py
- resolwe_bio/processes/expression/featureCounts.yml
- resolwe_bio/processes/expression/htseq_count.yml
- resolwe_bio/processes/import_data/annotation.yml
- resolwe_bio/processes/import_data/cuffquant.yml
- resolwe_bio/processes/import_data/differential_exp.yml
- resolwe_bio/processes/import_data/expressions.yml
- resolwe_bio/processes/import_data/geneset.yml
- resolwe_bio/processes/import_data/microarray_affy.yml
- resolwe_bio/tests/generators/test_management_commands.py
- resolwe_bio/tests/processes/test_alignment.py
- resolwe_bio/tests/processes/test_clustering.py
- resolwe_bio/tests/processes/test_diff_expression.py
- resolwe_bio/tests/processes/test_expression.py
- resolwe_bio/tests/processes/test_gencover.py
- resolwe_bio/tests/processes/test_genome_coverage.py
- resolwe_bio/tests/processes/test_microarray.py
- resolwe_bio/tests/processes/test_support_processors.py
- resolwe_bio/tests/processes/test_upload.py
- resolwe_bio/utils/test.py
* Fix handling of big inputs
* Add sample name to Data object's name
> Fix htseq_count and featureCount

- resolwe_bio/signals.py
- resolwe_bio/tests/unit/test_signals.py
- resolwe_bio/tests/unit/test_views.py
- resolwe_bio/views.py
Requires: https://github.com/genialis/resolwe/pull/150
> Unify handling of Samples

- docs/CHANGELOG.rst
- resolwe_bio/kb/search_indexes.py
- resolwe_bio/kb/tests/test_feature.py
- resolwe_bio/kb/views.py
Deployment consideration:
* Knowledge base search indices must be rebuilt.
> Add feature search filter by source

- resolwe_bio/kb/search_indexes.py
- resolwe_bio/kb/views.py
This reverts commit f9709c3c05a87c53dbb0541ea3583cae4395bdaf.
> Revert "Fix kb autocomplete ordering"

- resolwe_bio/kb/apps.py
- resolwe_bio/kb/search_indexes.py
- resolwe_bio/kb/views.py
This PR contains a workaround for buggy Haystack mapping for edgengram-based fields.
Requires index rebuild.
> Fix feature autocomplete result order

- resolwe_bio/kb/models.py
- resolwe_bio/kb/search_indexes.py
- resolwe_bio/kb/serializers.py
- resolwe_bio/kb/tests/test_mapping.py
- resolwe_bio/kb/views.py
- tests/urls.py
Make the endpoints more similar to how features are handled. Also adds support for adding new mappings using the API.
Requires index rebuild.
> Refactor knowledge base mapping endpoints

- .travis.yml
- resolwe_bio/kb/elastic_indexes.py
- resolwe_bio/kb/serializers.py
- resolwe_bio/kb/tests/test_feature.py
- resolwe_bio/kb/views.py
- tests/docker-compose.yml
- tests/settings.py
- tests/urls.py
Requires genialis/resolwe#185.
> Use new ES API for feature search

- resolwe_bio/processes/chip_seq/macs14.yml
- resolwe_bio/processes/chip_seq/rose2.yml
- resolwe_bio/tests/processes/test_chipseq.py
@jkokosar please review if chosen names are suitable
> Use more verbose names in rose2 and macs14

- resolwe_bio/kb/management/commands/insert_features.py
> Faster feature import

- resolwe_bio/kb/tests/test_feature.py
- resolwe_bio/kb/views.py
> Fix feature query to not hit the clause limit

- README.rst
- docs/CHANGELOG.rst
- docs/conf.py
- docs/index.rst
- resolwe_bio/__about__.py
- setup.py
- tox.ini
@jkokosar, please check if the Change Log includes all notable changes from release 1.2.1.
> Prepare release 1.3.0

- MANIFEST.in
- docs/CHANGELOG.rst
- docs/conf.py
- docs/contributing.rst
- resolwe_bio/kb/tests/test_feature.py
- resolwe_bio/kb/tests/test_mapping.py
- resolwe_bio/kb/views.py
- resolwe_bio/models.py
- resolwe_bio/signals.py
- resolwe_bio/tests/processes/test_processor.py
- resolwe_bio/utils/test.py
- setup.py
- tests/settings.py
- tox.ini
Depends on https://github.com/genialis/resolwe/pull/208
> Support resolwe test framework

- tests/settings.py
Requires https://github.com/genialis/resolwe/pull/223
> Rename RESOLWE_API_HOST setting to RESOLWE_HOST_URL

- resolwe_bio/processes/chip_seq/rose2.yml
- resolwe_bio/tools/plot_enhancers.py
> Fix-rose2 to store jason files

- docs/CHANGELOG.rst
- resolwe_bio/processes/alignment/star.yml
> Add filtering option to star aligner

- docs/CHANGELOG.rst
- resolwe_bio/descriptors/sample_geo.yml
> Fix sample desctiptor to show strain option for any organism

- resolwe_bio/descriptors/bcm.yml
- resolwe_bio/processes/workflows/chip_seq.yml
- resolwe_bio/tests/workflows/test_chip_seq.py
> Recipes page for BCM and chip-seq workflow

- resolwe_bio/filters.py
The question is are these patches even necessary? Why not use `entity` in the first place or is `sample` used for backwards compatibility?
> Fix filters

- docs/CHANGELOG.rst
- resolwe_bio/descriptors/bbduk-star-htseq.yml
> Change rna-seq schema (field starnded)

- resolwe_bio/descriptors/bcm.yml
Please review and merge into master.
> Incremented version, fixed labels

- docs/CHANGELOG.rst
- resolwe_bio/kb/tests/test_feature.py
- resolwe_bio/kb/views.py
- resolwe_bio/tools/goea.py
Rebased on https://github.com/genialis/resolwe-bio/pull/278
> Fix goea feature query

- docs/CHANGELOG.rst
- resolwe_bio/descriptors/bbduk-star-htseq.yml
https://github.com/genialis/bug-reports/issues/15
Fix protocol labels following the suggestion by @rafecooks.
> Fix protocol labels in rna-seq-quantseq descriptor schema

- resolwe_bio/descriptors/rnaseq.yml
- resolwe_bio/processes/workflows/rnaseq.yml
- resolwe_bio/tools/rnaseq.py
This pull request does not contain RNA-Seq DSS test.
> Add RNA-Seq decision support system and descriptor schema

- docs/CHANGELOG.rst
- resolwe_bio/descriptors/sample_geo.yml
Please review and merge into master.
> Add S. tuberosum choice to sample descriptor schema

- resolwe_bio/processes/icount/annotation.yml
- resolwe_bio/processes/icount/genome.yml
- resolwe_bio/processes/variant_calling/snpeff.yml
Fix for process version not correctly bumped here: https://github.com/genialis/resolwe-bio/pull/285
> Bump snpEff process version

- docs/CHANGELOG.rst
- resolwe_bio/processes/clustering/hierarchical_clustering.yml
- resolwe_bio/tools/genehcluster.py
- resolwe_bio/tools/samplehcluster.py
Please review and merge into master.
> Add log2 to gene and sample hierarchical clustering

- docs/CHANGELOG.rst
- resolwe_bio/descriptors/diffexp.yml
> Set log(fc) default to 1 in diffexp descriptor schema

- docs/CHANGELOG.rst
- resolwe_bio/processes/alignment/star.yml
- resolwe_bio/processes/jbrowse/annotation_gff3.yml
- resolwe_bio/processes/jbrowse/annotation_gtf.yml
> Add memory as a resource in star and jbrowse annotation(gff3, gtf)  processes

- docs/CHANGELOG.rst
- resolwe_bio/descriptors/sample_geo.yml
- resolwe_bio/processes/alignment/bowtie.yml
- resolwe_bio/processes/chip_seq/macs14.yml
- resolwe_bio/processes/reads_processing/bbduk.yml
- resolwe_bio/processes/reads_processing/trimmomatic.yml
- resolwe_bio/processes/workflows/chip_seq.yml
- resolwe_bio/tests/processes/test_alignment.py
- resolwe_bio/tests/workflows/test_chip_seq.py
> Modify chip-seq processes

- resolwe_bio/descriptors/amplicon.yml
https://github.com/genialis/meta/issues/59
> Fix amplicon panel labels

- docs/CHANGELOG.rst
- resolwe_bio/descriptors/sample_geo.yml
> Add Odocoileus virginianus texanus organism to sample descriptor

- docs/CHANGELOG.rst
- docs/conf.py
- resolwe_bio/tests/processes/test_enrichment.py
- resolwe_bio/utils/test.py
- setup.py
These are non-problematic commits from PR #216 that can be merged independently.
> Miscellaneous improvements

- docs/CHANGELOG.rst
- resolwe_bio/__about__.py
- setup.py
- tests/urls.py
Needs genialis/resolwe#352 to be accepted and Resolwe release 2.0.0 made available.
> Prepare release 2.0.0 and bump version to 2.1.0a1

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/rnaseq/Dockerfile
- resolwe_bio/docker_images/rnaseq/README.md
@jkokosar @mstajdohar @dblenkus
> Add RNA-seq dockerfile

- docs/CHANGELOG.rst
- resolwe_bio/descriptors/bcm.yml
@jkokosar @mstajdohar @dblenkus
> Add Mus musculus to all BCM workflows' schemas

- docs/CHANGELOG.rst
- resolwe_bio/descriptors/reads.yml
> Add antibody information to reads descriptor schema

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/rnaseq/packages-manual.txt
- resolwe_bio/docker_images/rnaseq/packages-manual/cufflinks.sh
- resolwe_bio/docker_images/rnaseq/packages-manual/r-packages.sh
- resolwe_bio/docker_images/rnaseq/packages-r-bioconductor.txt
- resolwe_bio/docker_images/rnaseq/packages-r.txt
> Add cufflinks and RNASeqT R library to resolwebio/rnaseq docker image

- docs/CHANGELOG.rst
- resolwe_bio/processes/amplicon/bwa_trim.yml
Requires https://github.com/genialis/resolwe-bio/pull/409
> Use resolwebio/dnaseq docker image in align-bwa-trim process

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/chipseq/packages-manual/wigtobigwig.sh
> Add wigtobigwig.sh to chipseq docker image folder

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/dnaseq/README.md
- resolwe_bio/docker_images/dnaseq/packages-debian-buildreq.txt
- resolwe_bio/docker_images/dnaseq/packages-debian.txt
- resolwe_bio/docker_images/dnaseq/packages-manual.txt
- resolwe_bio/docker_images/dnaseq/packages-manual/r-packages.sh
- resolwe_bio/docker_images/dnaseq/packages-r-bioconductor.txt
- resolwe_bio/docker_images/dnaseq/packages-r.txt
> Add chemut R library to resolwebio/dnaseq Docker image

- resolwe_bio/processes/import_data/pathway_map.yml
- resolwe_bio/tests/processes/test_pathway_map.py
~ with species and source field
> Extend pathway map uploader process

- docs/CHANGELOG.rst
- resolwe_bio/processes/variant_calling/filtering_chemut.yml
> Use resolwebio/dnaseq:1.2.0 docker in filtering_chemut process

- README.rst
- docs/CHANGELOG.rst
- docs/contributing.rst
- resolwe_bio/__about__.py
- tox.ini
In addition, I've updated the docs and prettified the tox.ini file.
> Prepare release 6.2.0 and bump version to 6.3.0a1

- resolwe_bio/processes/annotation/cuffmerge.yml
- resolwe_bio/processes/clustering/hierarchical_clustering.yml
- resolwe_bio/processes/clustering/pca.yml
- resolwe_bio/processes/differential_expression/cuffdiff.yml
- resolwe_bio/processes/differential_expression/deseq.yml
- resolwe_bio/processes/differential_expression/edgeR.yml
- resolwe_bio/processes/differential_expression/limma.yml
- resolwe_bio/processes/expression/expression_aggregator.yml
- resolwe_bio/processes/expression/index_fasta_nucl.yml
- resolwe_bio/processes/expression/merge_expressions.yml
- resolwe_bio/processes/go_enrichment/go.yml
- resolwe_bio/tools/expression_aggregator.py
> Change error messages 

- docs/CHANGELOG.rst
- resolwe_bio/processes/chip_seq/macs14.yml
- resolwe_bio/processes/import_data/bam.yml
- resolwe_bio/processes/support_processors/bam_split.yml
- resolwe_bio/processes/workflows/chip_seq.yml
- resolwe_bio/tests/processes/test_chipseq.py
- resolwe_bio/tests/processes/test_support_processors.py
- resolwe_bio/tests/workflows/test_chip_seq.py
@jkokosar @mstajdohar @dblenkus 
Includes https://github.com/genialis/resolwe-bio/pull/400
> Refactor macs14 process

- docs/CHANGELOG.rst
- setup.py
Same as #469, opened to check if Jenkins will make a different git checkout this time.
> Another try at bumping Resolwe to version 7.x

- docs/CHANGELOG.rst
- resolwe_bio/processes/variant_calling/vc_chemut.yml
- resolwe_bio/processes/workflows/chemut.yml
@jkokosar @dblenkus @tjanez 
Is 32GB enough?
> Fix chemut memory limit and data type

- docs/CHANGELOG.rst
- resolwe_bio/processes/support_processors/prepare_geo.yml
- resolwe_bio/tests/files/prepare_geo_ChIP-Seq.txt
- resolwe_bio/tests/files/prepare_geo_RNA-Seq.txt
- resolwe_bio/tests/processes/test_support_processors.py
> Add 'prepare-geo-chipseq' and 'prepare-geo-rnaseq' processes

- docs/CHANGELOG.rst
Some errors were still left in the changelog. Thank you @mzganec for pointing them out. This PR should fix them. @mzganec can you please review?
> Fix errors in CHANGELOG

- docs/CHANGELOG.rst
- resolwe_bio/descriptors/cutadapt-star-htseq.yml
- resolwe_bio/descriptors/rnaseq.yml
Requires https://github.com/genialis/genialis-bio/pull/18
> Rename the organism field names to species in rna-seq and cutadapt-star-htseq descriptor schemas

- docs/CHANGELOG.rst
- resolwe_bio/processes/workflows/chemut.yml
- resolwe_bio/tests/workflows/test_chemut.py
> Expose advanced parameters in chemut workflow

- docs/CHANGELOG.rst
- resolwe_bio/descriptors/bcm.yml
- resolwe_bio/descriptors/dicty.yml
Rename the genome_and_annotation field name to
species in related descriptor schemas
> Use species full name in bcm-* descriptor schemas

- docs/CHANGELOG.rst
- resolwe_bio/processes/expression/dicty_bcm.yml
- resolwe_bio/tests/processes/test_expression.py
Related to https://github.com/genialis/meta/issues/211
@rafecooks @jkokosar
> Rename Expressions (BCM) to Dicty expressions

- docs/CHANGELOG.rst
- resolwe_bio/processes/variant_calling/filtering_chemut.yml
- resolwe_bio/processes/workflows/chemut.yml
> Use resolwebio/dnaseq:3.0.0 image in filtering_chemut process

- resolwe_bio/kb/views.py
Closes https://github.com/genialis/resolwe-bio/issues/520
> Fix signatures of create functions in kb views

- docs/CHANGELOG.rst
- resolwe_bio/processes/support_processors/archive.yml
- resolwe_bio/tools/expressionmerge_archive.py
- resolwe_bio/tools/make_igv_session_archive.py
This is fix for https://github.com/genialis/meta/issues/226
@jkokosar @JureZmrzlikar please review
> Fix merge expression to use sample names

- docs/CHANGELOG.rst
- resolwe_bio/kb/admin.py
- resolwe_bio/kb/models.py
- resolwe_bio/tests/files/igv_session_bam.xml
- resolwe_bio/tests/processes/test_genome_browser.py
- resolwe_bio/tools/goea.py
- tests/settings.py
Improving robustness of `goea.py` tool, debuggability of `Feature` and `Mapping` models and ensuring no tests could ever connect to `qa2.genialis.com` server.
> Miscellaneous minor improvements

- resolwe_bio/extensions.py
- resolwe_bio/kb/tests/test_feature.py
- resolwe_bio/kb/tests/test_mapping.py
- resolwe_bio/kb/views.py
- resolwe_bio/tests/unit/test_api.py
- resolwe_bio/utils/test.py
> Add resolwe-bio extensions of Resolwe core

- resolwe_bio/descriptors/bbduk-star-featurecounts.yml
- resolwe_bio/processes/workflows/bbduk_star_featurecounts.yml
This change is needed to avoid ASCII error in Ansible.
> Change backtick to apostrophe in RNA-seq description

- resolwe_bio/descriptors/reads_detailed.yml
- resolwe_bio/descriptors/transmart.yml
- resolwe_bio/processes/import_data/nucleotide_seq.yml
These errors were identified with newly implemented process
validation.
> Fix some names and defaults

- MANIFEST.in
- docs/CHANGELOG.rst
- resolwe_bio/docker_images/dnaseq/Dockerfile
- resolwe_bio/docker_images/dnaseq/README.md
- resolwe_bio/docker_images/dnaseq/assets/amplicon_html_template.html
- resolwe_bio/docker_images/dnaseq/packages-manual.txt
- resolwe_bio/docker_images/dnaseq/packages-manual/bokeh-assets.sh
- resolwe_bio/docker_images/dnaseq/packages-manual/snpeff.sh
- resolwe_bio/docker_images/latex/assets/template_amplicon_report.tex
Requires https://github.com/genialis/resolwe-bio/pull/524
> Add amplicon report assets to resolwebio/latex and resolwebio/dnaseq images

- docs/CHANGELOG.rst
- resolwe_bio/processes/expression/cufflinks.yml
- resolwe_bio/processes/expression/cuffnorm.yml
- resolwe_bio/processes/expression/cuffquant.yml
- resolwe_bio/tests/processes/test_expression.py
> Fix source tracking in cufflinks and cuffquant processes

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/chipseq/README.md
- resolwe_bio/docker_images/chipseq/packages-debian.txt
- resolwe_bio/docker_images/chipseq/packages-manual.txt
- resolwe_bio/docker_images/chipseq/packages-manual/bedgraphtobigwig.sh
- resolwe_bio/docker_images/chipseq/packages-manual/bedops.sh
- resolwe_bio/docker_images/chipseq/packages-manual/bedtobigbed.sh
- resolwe_bio/docker_images/chipseq/packages-manual/wigtobigwig.sh
- resolwe_bio/docker_images/rnaseq/README.md
- resolwe_bio/docker_images/rnaseq/packages-manual.txt
- resolwe_bio/docker_images/rnaseq/packages-manual/genome-tools.sh
- resolwe_bio/docker_images/rnaseq/packages-manual/igvtools.sh
- resolwe_bio/docker_images/rnaseq/packages-manual/jbrowse.sh
@kostko @JureZmrzlikar please review. I have added changes under Unreleased.
> Add tools to support genome browsers to chipseq and resolwebio Docker images

- .github/pull_request_template.md
- setup.cfg
With an aim to make writing and reviewing PRs easier and requirements more clear I have made PR checklist and guidelines for Resolwe-bio repository.
Please comment and contribute.
Thanks
> Add PR template checklist and guidelines

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/rnaseq/README.md
- resolwe_bio/docker_images/rnaseq/packages-debian.txt
- resolwe_bio/docker_images/rnaseq/packages-manual.txt
- resolwe_bio/docker_images/rnaseq/packages-manual/bedgraphtobigwig.sh
> Add aligners to resolwebio/rnaseq Docker image

- docs/CHANGELOG.rst
- resolwe_bio/processes/import_data/seq_reads.yml
- resolwe_bio/processes/reads_processing/bbduk.yml
- resolwe_bio/processes/reads_processing/cutadapt.yml
- resolwe_bio/processes/reads_processing/cutadapt_custom.yml
- resolwe_bio/processes/reads_processing/merge_to_paired_end.yml
- resolwe_bio/processes/reads_processing/trimmomatic.yml
This update unifies the version of `FastQC` tool used for quality control of reads.
commit(s).
input parameter, use a different tool that produces …
> Use resolwebio/rnaseq:3.2.0 Docker image in processes that output reads

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/rnaseq/packages-debian.txt
> Add package file to resolwebio/rnaseq Docker image

- docs/CHANGELOG.rst
- resolwe_bio/processes/reports/amplicon_multi_report.yml
- resolwe_bio/processes/support_processors/archive.yml
- resolwe_bio/tests/processes/test_generate_report.py
> Fix archiver processes to correctly handle linking of nested file paths

- docs/CHANGELOG.rst
- resolwe_bio/descriptors/bbduk-star-featurecounts.yml
Move assay type input in the descriptor schema to advanced options.
commit(s).
* …
> Move assay type input in the new RNA-seq descriptor schema to advanced options

- docs/CHANGELOG.rst
- resolwe_bio/processes/alignment/star.yml
- resolwe_bio/tests/processes/test_alignment.py
> Use resolwebio/rnaseq Docker image in STAR index

- docs/CHANGELOG.rst
- resolwe_bio/processes/alignment/bowtie.yml
- resolwe_bio/processes/alignment/bwa.yml
- resolwe_bio/processes/alignment/hisat2.yml
- resolwe_bio/processes/alignment/star.yml
- resolwe_bio/processes/alignment/subread.yml
- resolwe_bio/processes/alignment/tophat.yml
- resolwe_bio/tools/bamtobigwig.sh
> Use deepTools to create BigWig from Bam

- resolwe_bio/processes/chip_seq/macs14.yml
- resolwe_bio/tools/bed_file_corrections_genome_browsers.py
> Fix MACS1.4

- docs/CHANGELOG.rst
- resolwe_bio/processes/alignment/star.yml
> Add outFilterMismatchNoverReadLmax input to alignment-star process

- docs/CHANGELOG.rst
- resolwe_bio/processes/expression/cuffnorm.yml
- resolwe_bio/tools/parse_cuffnorm.py
@jkokosar
commit(s).
* **PATCH version (last number)**: changes/bug fixes that do …
> Make cuffnorm attach correct expression data objects to samples

- docs/CHANGELOG.rst
- resolwe_bio/processes/import_data/sra_file.yml
- resolwe_bio/tests/processes/test_import.py
> Check for errors during download of FASTQ files in SRA import process

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/rnaseq/packages-manual.txt
- resolwe_bio/docker_images/rnaseq/packages-manual/chrom-mappings.sh
> Add chromosome mappings to rnaseq docker image

- docs/CHANGELOG.rst
- resolwe_bio/processes/import_data/seq_reads.yml
> Improve helper text and labels in reads upload processes

- docs/CHANGELOG.rst
- resolwe_bio/processes/chip_seq/rose2.yml
@jkokosar @JenkoB 
commit(s).
* **PATCH version (last number)**: changes/bug fixes …
> Fix and improve rose2 error messages

- docs/CHANGELOG.rst
- resolwe_bio/processes/expression/featureCounts.yml
- resolwe_bio/processes/workflows/bbduk_star_featurecounts.yml
- resolwe_bio/tests/processes/test_expression.py
- resolwe_bio/tools/detect_strandedness.sh
> Use read count instead of sampling rate in strandedness detection

- docs/CHANGELOG.rst
- resolwe_bio/processes/chip_seq/rose2.yml
- resolwe_bio/processes/workflows/chip_seq.yml
- resolwe_bio/tests/processes/test_chipseq.py
- resolwe_bio/tests/workflows/test_chip_seq.py
@jkokosar @JenkoB 
commit(s).
* **PATCH version (last number)**: changes/bug fixes …
> Remove 'genome' input and fix 'stitch' parameter handling in rose2

- docs/CHANGELOG.rst
- resolwe_bio/processes/alignment/star.yml
- resolwe_bio/tests/processes/test_alignment.py
> Add two-pass mode to alignment-star process

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/rnaseq/README.md
- resolwe_bio/docker_images/rnaseq/packages-debian-buildreq.txt
- resolwe_bio/docker_images/rnaseq/packages-manual.txt
- resolwe_bio/docker_images/rnaseq/packages-manual/regtools.sh
> Add regtools to resolwebio/rnaseq Docker image

- docs/CHANGELOG.rst
- resolwe_bio/descriptors/kapa.yml
- resolwe_bio/processes/workflows/bbduk_star_featurecounts.yml
- resolwe_bio/tests/workflows/test_rna_seq.py
> Allow using custom adapter sequences in RNA-seq workflow

- docs/CHANGELOG.rst
- resolwe_bio/processes/import_data/sra_file.yml
> Reduce RAM requirement in SRA import processes

- resolwe_bio/descriptors/cutadapt-star-featurecounts.yml
- resolwe_bio/processes/workflows/cutadapt_star_featurecounts.yml
> Fix workflow and descriptor schema for cuatadapt-star-fc

- resolwe_bio/docker_images/rnaseq/packages-manual/chrom-mappings.sh
> Fix chromosome mappings file name in resolwebio/rnaseq Docker image

- resolwe_bio/tools/bigwig_chroms_to_ucsc.py
> Skip contigs with missing UCSC mappings in BigWig

- resolwe_bio/processes/alignment/bowtie.yml
- resolwe_bio/processes/import_data/sra_file.yml
- resolwe_bio/processes/workflows/bbduk_star_htseq.yml
Replace invlaid unicode characters
Increase process versions
commit(s).
* **PATCH …
> Fix registration errors

- docs/CHANGELOG.rst
- resolwe_bio/kb/management/commands/insert_features.py
- resolwe_bio/kb/management/commands/insert_mappings.py
- resolwe_bio/kb/management/commands/utils.py
- resolwe_bio/kb/models.py
- resolwe_bio/kb/tests/test_import_kb.py
- setup.py
- tests/docker-compose.yml
**Important:** This requires PostgreSQL 9.5
Requires https://github.com/genialis/resolwe/pull/378
> Speed-up insert management commands in kb

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/rnaseq/README.md
- resolwe_bio/docker_images/rnaseq/packages-debian.txt
- resolwe_bio/docker_images/rnaseq/packages-manual.txt
- resolwe_bio/docker_images/rnaseq/packages-manual/bedtobigbed.sh
- resolwe_bio/docker_images/rnaseq/packages-manual/cufflinks.sh
> Add tools for genome browsers to rnaseq docker

- docs/CHANGELOG.rst
- resolwe_bio/descriptors/amplicon.yml
> Add HS Panel choice to the amplicon descriptor schema

- docs/CHANGELOG.rst
- resolwe_bio/processes/support_processors/archive.yml
- resolwe_bio/tests/processes/test_support_processors.py
> Fix handling of exp objects in archive-samples

- resolwe_bio/processes/junctions/regtools.yml
- resolwe_bio/tools/star_sj_to_bed12.py
> Fix star_to_bed12.py script

- docs/CHANGELOG.rst
- resolwe_bio/descriptors/kapa.yml
> Expand kit selection choices in KAPA desc. schema

- resolwe_bio/processes/chip_seq/prepeak_qc.yml
This bug is blocking staging deploys.
> Fix non-ascii characters in process code

- docs/CHANGELOG.rst
- resolwe_bio/expression_filters/relation.py
- resolwe_bio/processes/expression/cuffnorm.yml
- resolwe_bio/processes/junctions/regtools.yml
- resolwe_bio/tests/processes/test_expression.py
- resolwe_bio/tests/processes/test_junctions.py
- resolwe_bio/tests/unit/test_expression_filters.py
- resolwe_bio/tools/novel_splice_junctions.py
- resolwe_bio/tools/star_sj_to_bed12.py
- tests/settings.py
> Add novel splice junctions in BED12 format output

- docs/CHANGELOG.rst
- resolwe_bio/expression_filters/relation.py
- resolwe_bio/processes/expression/cuffnorm.yml
- resolwe_bio/tests/processes/test_expression.py
- resolwe_bio/tests/unit/test_expression_filters.py
- tests/settings.py
> Sample relations in Cuffnorm

- resolwe_bio/processes/chip_seq/prepeak_qc.yml
> Add TMP_DIR to Picard MarkDuplicates in qc-prepeak

- resolwe_bio/processes/chip_seq/prepeak_qc.yml
> Fix line continuation error in qc-prepeak

- resolwe_bio/processes/chip_seq/prepeak_qc.yml
> Set JVM memory requirements in qc-prepeak process

- tests/manage.py
> Fix logging compatibility with the latest Channels

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/rnaseq/README.md
- resolwe_bio/docker_images/rnaseq/packages-manual.txt
- resolwe_bio/docker_images/rnaseq/packages-manual/makedb-walt.sh
- resolwe_bio/docker_images/wgbs/Dockerfile
- resolwe_bio/docker_images/wgbs/README.md
- resolwe_bio/docker_images/wgbs/packages-debian-buildreq.txt
- resolwe_bio/docker_images/wgbs/packages-debian.txt
- resolwe_bio/docker_images/wgbs/packages-manual.txt
- resolwe_bio/docker_images/wgbs/packages-manual/methpipe.sh
- resolwe_bio/docker_images/wgbs/packages-manual/walt.sh
commit(s).
* **PATCH version (last number)**: changes/bug …
> Put WGBS tools in docker images

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/wgbs/README.md
- resolwe_bio/docker_images/wgbs/packages-manual.txt
- resolwe_bio/docker_images/wgbs/packages-manual/wigtobigwig.sh
> Add wigToBigWig tool to resolwebio/wgbs docker image

- docs/CHANGELOG.rst
- resolwe_bio/processes/amplicon/amplicon_table.yml
- resolwe_bio/tools/make_amplicon_table.py
> Fix amplicon table gene hyperlinks

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/common/packages-debian.txt
- resolwe_bio/docker_images/common/packages-manual/chrom-mappings.sh
> Update mappings docker

- docs/CHANGELOG.rst
- resolwe_bio/processes/chip_seq/macs14.yml
- resolwe_bio/processes/chip_seq/macs2.yml
- resolwe_bio/processes/chip_seq/rose2.yml
> Attach MACS data to case/treatment sample

- docs/CHANGELOG.rst
- resolwe_bio/processes/import_data/genome.yml
- resolwe_bio/processes/reads_processing/trimmomatic.yml
Affected processes:
* upload-genome
* trimmomatic-single
* trimmomatic-paired
commit(s). …
> Set Docker memory limits

- docs/CHANGELOG.rst
- resolwe_bio/expression_filters/relation.py
- resolwe_bio/tests/unit/test_expression_filters.py
> Add expression filter for background pairs

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/dnaseq/Dockerfile
- resolwe_bio/docker_images/dnaseq/README.md
- resolwe_bio/docker_images/dnaseq/packages-debian.txt
- resolwe_bio/docker_images/dnaseq/packages-manual/gatk.sh
Add JDK v8 and use it by default
Bump GATK4 version to 4.0.11.0
commit(s).
* …
> Update resolwebio/dnaseq Docker image

- docs/CHANGELOG.rst
- resolwe_bio/processes/alignment/star.yml
- resolwe_bio/processes/reads_processing/bbduk.yml
> STAR and BBDuk process tuning

- docs/CHANGELOG.rst
- resolwe_bio/__about__.py
> Release 2018-12-19

- docs/CHANGELOG.rst
- resolwe_bio/processes/alignment/bwa.yml
- tox.ini
alignment-bwa-aln
alignment-bwa-sw
commit(s). …
> Enable multithreading in BWA processes

- docs/CHANGELOG.rst
- resolwe_bio/processes/WGBS/walt.yml
The sort command buffer size was limited to the process memory limit.
commit(s).
* …
> Fix walt getting killed when sort runs out of memory

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/rnaseq/README.md
- resolwe_bio/docker_images/rnaseq/packages-manual/star.sh
> Bump STAR aligner to v2.7.0a in resolwebio/rnaseq Docker

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/rnaseq/README.md
- resolwe_bio/docker_images/rnaseq/packages-manual/star.sh
> Bump STAR to 2.7.0c in resolwebio/rnaseq

- docs/CHANGELOG.rst
- resolwe_bio/processes/alignment/star.yml
Requires https://github.com/genialis/resolwe-bio/pull/727
> Use resolwebio/rnaseq:4.2.2 in STAR

- docs/CHANGELOG.rst
- resolwe_bio/__about__.py
> Release 16.3

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/common/README.md
- resolwe_bio/docker_images/common/packages-manual/subread.sh
> Bump Subread package to 1.6.3

- docs/CHANGELOG.rst
- resolwe_bio/processes/reads_processing/bbduk.yml
- resolwe_bio/processes/workflows/bbduk_star_featurecounts.yml
- resolwe_bio/processes/workflows/bbduk_star_featurecounts_qc.yml
> Expose maxns parameter in bbduk processes

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/rnaseq/Dockerfile
> Use resolwebio/common:1.1.0 in rnaseq Docker

- docs/CHANGELOG.rst
- resolwe_bio/processes/expression/featureCounts.yml
Requires https://github.com/genialis/resolwe-bio/pull/736
> Use resolwebio/rnaseq:4.3.0 in feature_counts

- resolwe_bio/processes/chip_seq/macs2_batch.yml
- resolwe_bio/processes/chip_seq/macs2_rose2_batch.yml
- resolwe_bio/processes/expression/cuffnorm.yml
> Support relations requirements in macs2 and cuffnorm

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/scseq/Dockerfile
- resolwe_bio/docker_images/scseq/README.md
- resolwe_bio/docker_images/scseq/packages-manual.txt
- resolwe_bio/docker_images/scseq/packages-manual/cellranger.sh
> Add resolwebio/scseq docker image

- docs/CHANGELOG.rst
- resolwe_bio/processes/support_processors/seqtk.yml
- resolwe_bio/tools/detect_strandedness.sh
> Small fixes

- resolwe_bio/docker_images/scseq/packages-manual/cellranger.sh
- resolwe_bio/processes/scseq/cellranger.py
> Fix cellranger-count html report build

- docs/CHANGELOG.rst
- resolwe_bio/processes/scseq/cellranger.py
@mstajdohar 
Waiting on: https://github.com/genialis/resolwe-bio/pull/751
> Fix 'cellranger-count' html report

- docs/CHANGELOG.rst
- resolwe_bio/processes/workflows/cuffquant.yml
> Use XS flag in workflow-rnaseq-cuffquant alignment

- MANIFEST.in
- pyproject.toml
- resolwe_bio/__about__.py
- resolwe_bio/tools/basespace_download.py
- resolwe_bio/tools/demultiplex.py
- resolwe_bio/tools/etc.py
- resolwe_bio/tools/genehcluster.py
- resolwe_bio/tools/make_amplicon_table.py
- resolwe_bio/tools/make_multireport.py
- resolwe_bio/tools/make_report.py
- resolwe_bio/tools/plotcoverage_html.py
- resolwe_bio/tools/samplehcluster.py
- resolwe_bio/tools/star_sj_to_bed12.py
- setup.cfg
- setup.py
- tox.ini
> Improve project's infrastructure

- docs/CHANGELOG.rst
- resolwe_bio/processes/support_processors/archive.yml
- resolwe_bio/tests/processes/test_chipseq.py
@jkokosar 
commit(s).
* **PATCH version (last number)**: changes/bug fixes that do …
> Fix archive-samples to work when downloading only peaks

- docs/CHANGELOG.rst
- resolwe_bio/processes/import_data/seq_reads_10x.py
- resolwe_bio/processes/scseq/cellranger.py
commit(s).
* **PATCH version (last number)**: changes/bug …
> Simplify cellranger-count outputs' folder structure

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/rnaseq/README.md
- resolwe_bio/docker_images/rnaseq/packages-manual/star.sh
> Bump STAR version in resolwebio/rnaseq Docker image

- docs/CHANGELOG.rst
- resolwe_bio/processes/import_data/geneset.yml
- resolwe_bio/tools/geneset2storage.py
> Fix parsing empty gene set files

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/common/packages-manual/qorts.sh
> Expose memory usage flags in QoRTs tool

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/rnaseq/Dockerfile
> Use resolwebio/common:1.1.3 in resolwebio/rnaseq

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/wgbs/README.md
- resolwe_bio/docker_images/wgbs/packages-debian.txt
> Add Tabix to resolwebio/wgbs docker image

- docs/CHANGELOG.rst
- resolwe_bio/processes/WGBS/hmr.yml
Docker image from https://github.com/genialis/resolwe-bio/pull/775 has to be built for the tests to pass.
commit(s).
input …
> Add Jbrowse index output to hmr process

- docs/CHANGELOG.rst
- resolwe_bio/processes/support_processors/multiqc.yml
- resolwe_bio/processes/support_processors/qorts_qc.py
> Bump QoRTs and MultiQC memory requirements

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/dnaseq/README.md
- resolwe_bio/docker_images/dnaseq/packages-debian.txt
- resolwe_bio/docker_images/dnaseq/packages-manual.txt
- resolwe_bio/docker_images/dnaseq/packages-manual/bamclipper.sh
- resolwe_bio/docker_images/dnaseq/packages-manual/gatk.sh
- resolwe_bio/docker_images/dnaseq/packages-manual/r-packages.sh
A bamclipper tool is added to `resolwebio/dnaseq`. GATK has been bumped to latest version 4.1.2.0. I would recommend tagging this docker image as 4.2.0.
In addition, building of the image was interrupted when building `chemut` R package dependency `assertthat`.
```
Error in run(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout),  : 
lazy-load database '/usr/local/lib/R/site-library/assertthat/R/assertthat.rdb' is corrupt
Calls: install_github ... with.default -> eval -> eval -> with_envvar -> force -> run
In addition: Warning message:
In run(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout),  :
internal error -3 in R_decompress1
Execution halted
xargs: bash: exited with status 255; aborting
```
The root cause is not exactly known (possibly due to …
> Add bamclipper tool to dnaseq docker and fix building issues

- docs/CHANGELOG.rst
- resolwe_bio/processes/import_data/bam.yml
- resolwe_bio/processes/support_processors/bam_split.yml
commit(s).
* **PATCH version (last number)**: changes/bug …
> Support hg19_mm10 hybrid genome in bam-split process

- docs/CHANGELOG.rst
- resolwe_bio/processes/support_processors/multiqc.yml
> Use MultiQC configuration file by default in multiqc process

- resolwe_bio/processes/reads_processing/trimmomatic.yml
> Fix adapter file handling in Trimmomatic

- resolwe_bio/processes/support_processors/multiqc.yml
> Set dirs and config inputs to True in multiqc

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/dnaseq/Dockerfile
Common image (`resolwebio/common`) is bumped to version `resolwebio/common:1.1.3` in `resolwebio/dnaseq:4.2.0`. 
commit(s). …
> Bump common image in resolwebio/dnaseq to 1.1.3

- resolwe_bio/processes/reads_processing/bqsr.py
- resolwe_bio/processes/reads_processing/markduplicates.py
- resolwe_bio/processes/workflows/wes.yml
This is a patch that fixes a bug in `markduplicates `. It also fixes the missing entry in dropdown menu of `assume_sort_order`.
In addition, it revises labels and descriptions of `bqsr` and `markduplicates` processes.
Bumps versions of all changed processes.
commit(s).
* **MINOR version (middle …
> Fix bugs in WES workflow and accompanying processes

- docs/CHANGELOG.rst
- resolwe_bio/processes/alignment/bwa.yml
- resolwe_bio/processes/support_processors/seqtk.yml
> Bump cpu and memory resource allocation for some processes

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/rnaseq/README.md
- resolwe_bio/docker_images/rnaseq/packages-debian.txt
- resolwe_bio/docker_images/rnaseq/packages-manual/r-packages.sh
- resolwe_bio/docker_images/rnaseq/packages-manual/salmon.sh
- resolwe_bio/docker_images/rnaseq/packages-r-bioconductor.txt
- resolwe_bio/docker_images/rnaseq/packages-r.txt
> Bump Salmon to 0.14.0 in resolwebio/rnaseq Docker image and fix tximport installation

- README.rst
Rename domain name. The main purpose is to test jenkins automatic build triggers.
commit(s). …
> Change domain name

- resolwe_bio/processes/expression/salmon.py
> Fix bias correction warnings in Salmon

- docs/CHANGELOG.rst
- resolwe_bio/processes/expression/featureCounts.yml
- resolwe_bio/tools/expression_rpkum.py
Transition from `pandas.DataFrame` to `pandas.Series`.
> Improve performance of RPKUM normalization in featureCounts

- docs/CHANGELOG.rst
- resolwe_bio/processes/support_processors/spikeins_qc.yml
- resolwe_bio/tools/spikein_pairwise.py
> Fix spikeins-qc process to handle expressions without spikeins

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/common/packages-debian.txt
> Add pigz package to resolwebio/common Docker image

- docs/CHANGELOG.rst
- resolwe_bio/processes/chip_seq/macs2.yml
> Fix re-error bug in macs2-callpeak

- docs/CHANGELOG.rst
> Prepare release 21.0.1

- docs/CHANGELOG.rst
- resolwe_bio/processes/differential_expression/deseq.yml
- resolwe_bio/tools/deseq.R
> Expose BetaPrior parameter in DESeq2 process

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/base/Dockerfile.ubuntu-18.04
Enabled for Docker images build from
resolwebio/base:ubuntu-18.04 base image
commit(s). …
> Install R from CRAN-maintained repositories in Docker images build from resolwebio/base:ubuntu-18.04

- resolwe_bio/processes/workflows/cutadapt_star_stringtie.yml
- resolwe_bio/tools/create_expression_set.py
> Fix features filter in create_expression_set.py

- resolwe_bio/tools/create_expression_set.py
> Fix CHUNK_SIZE limit in create_expresion_set.py

- docs/CHANGELOG.rst
> Prepare release 22.0.0

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/common/assets/multiqc_config.yml
> Update MultiQC config file

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/rnaseq/README.md
- resolwe_bio/docker_images/rnaseq/packages-manual/jbrowse.sh
> Bump Jbrowse to 1.16.6 in resolwebio/rnaseq Docker image

- docs/CHANGELOG.rst
- resolwe_bio/processes/import_data/annotation.yml
- resolwe_bio/tests/processes/test_upload.py
Requires https://github.com/genialis/resolwe-bio/pull/822
> Index GTF/GFF features upon annotation file upload

- resolwe_bio/processes/workflows/bbduk_salmon_qc.yml
- remove non-ascii charater in process
- fix typo in input field description
commit(s). …
> Fix Salmon workflow input field descriptions

- docs/CHANGELOG.rst
> Prepare release 23.0.0

- docs/CHANGELOG.rst
- resolwe_bio/processes/differential_expression/deseq.yml
- resolwe_bio/tools/deseq.R
> Ignore Salmon transcript versions in DESeq2

- docs/CHANGELOG.rst
- resolwe_bio/descriptors/sample.yml
- resolwe_bio/processes/workflows/cutadapt_star_fc_quant_tf.yml
- resolwe_bio/tests/workflows/test_rna_seq.py
> Add alternative 3' mRNA-seq workflow (no rRNA/globin depletion detection)

- docs/CHANGELOG.rst
- resolwe_bio/tools/basespace_download.py
> Robust BaseSpace file download

- docs/CHANGELOG.rst
- resolwe_bio/processes/chip_seq/rose2.yml
This can be merged once https://github.com/genialis/resolwe-bio/pull/837 is merged and resolwebio/bamliquidator:1.1.0 built.
commit(s). …
> Use resolwebio/bamliquidator:1.1.0 in rose2 process

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/bamliquidator/README.md
- resolwe_bio/docker_images/bamliquidator/packages-debian.txt
- resolwe_bio/processes/chip_seq/rose2.yml
> Use resolwebio/bamliquidator:1.2.0 in rose2 process

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/bamliquidator/README.md
- resolwe_bio/docker_images/bamliquidator/packages-debian.txt
@jkokosar 
commit(s).
* **PATCH version (last number)**: changes/bug fixes that do …
> Add Tabix (1.7-2) to resolwebio/bamliquidator:1.2.0 docker image

- docs/CHANGELOG.rst
- resolwe_bio/processes/expression/slamdunk.py
- resolwe_bio/processes/support_processors/seqtk_reverse_complement.py
> Fix slamdunk and reverse complement processes

- docs/CHANGELOG.rst
- resolwe_bio/processes/alignment/bwa.yml
> Bump CPU, memory and Docker image requirements in BWA processes

- docs/CHANGELOG.rst
> Prepare release 24.0.0

- docs/CHANGELOG.rst
- resolwe_bio/processes/variant_calling/filtering_chemut.yml
- resolwe_bio/tools/append_sample_info.py
> Append sample info to summary in filtering-chemut

- resolwe_bio/processes/slamdunk/alleyoop_snpeval.py
- resolwe_bio/processes/slamdunk/alleyoop_utrrates.py
- resolwe_bio/processes/slamdunk/slam_count.py
- resolwe_bio/processes/workflows/slamdunk.yml
> Add read length input to alleyoop utr-rates and snpeval

- docs/CHANGELOG.rst
- setup.py
Readthedocs build fails because pyasn1 dependency is missing (dependency of service-identity), but it is not installed automatically. Pyasn1 package is temporarily included in setup.py.
commit(s).
backwards-compatible manner. …
> Fix readthedocs build by manually including pyasn1

- docs/CHANGELOG.rst
- setup.py
> Prepare release 25.0.0

- docs/CHANGELOG.rst
- resolwe_bio/processes/support_processors/multiqc.yml
- resolwe_bio/tools/multiqc_sample_info.py
A temporary solution until https://github.com/genialis/resolwe-bio/pull/862 is ready.
> Create Sample summary table in MultiQC reports

- docs/CHANGELOG.rst
- resolwe_bio/processes/alignment/bowtie.yml
> Bump memory/CPU requirements in alignment-bowtie2

- docs/CHANGELOG.rst
> Prepare release 25.1.0

- docs/CHANGELOG.rst
- resolwe_bio/processes/slamdunk/alleyoop_collapse.py
- resolwe_bio/processes/workflows/slamdunk.yml
- resolwe_bio/tests/files/slamseq/output/collapsed_tcount.txt
- resolwe_bio/tests/files/slamseq/output/hs_slamseq_tcount_collapsed.txt
- resolwe_bio/tests/processes/test_slamdunk.py
- normalize to TPM
- map gene_ids to gene_symbols
commit(s). …
> Update alleyoop-collapse process output

- docs/CHANGELOG.rst
- resolwe_bio/processes/expression/salmon.py
- resolwe_bio/processes/import_data/bam_scseq.py
- resolwe_bio/processes/import_data/seq_reads_10x.py
- resolwe_bio/processes/reads_processing/cutadapt_3prime.py
- resolwe_bio/processes/reads_processing/cutadapt_corall.py
- resolwe_bio/processes/scseq/cellranger.py
- resolwe_bio/processes/support_processors/umi_tools.py
> Fix handling of input file names in Python processes

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/wgbs/Dockerfile
- resolwe_bio/docker_images/wgbs/README.md
- resolwe_bio/docker_images/wgbs/packages-debian.txt
> Use resolwebio/common as a base image in resolwebio/wgbs Docker image

- docs/CHANGELOG.rst
- resolwe_bio/processes/chip_seq/macs2.yml
- resolwe_bio/processes/chip_seq/macs2_batch.yml
- resolwe_bio/processes/chip_seq/macs2_rose2_batch.yml
- resolwe_bio/processes/chip_seq/prepeak_qc.yml
- resolwe_bio/processes/workflows/atac_seq.yml
- resolwe_bio/processes/workflows/chip_seq.yml
- resolwe_bio/tests/processes/test_chipseq.py
> Support MultiQC reports in ChIP-seq workflows

- resolwe_bio/processes/support_processors/wgs_metrics.py
> Fix metrics class naming in wgs-metrics process

- docs/CHANGELOG.rst
> Prepare release 26.0.0

- docs/CHANGELOG.rst
- resolwe_bio/processes/import_data/genome.yml
> Fix jbrowse track creation in upload-genome process

- docs/CHANGELOG.rst
- resolwe_bio/processes/support_processors/rrbs_metrics.py
> Bump memory requirements in rrbs_metrics process

- resolwe_bio/processes/WGBS/bsrate.py
- resolwe_bio/processes/support_processors/multiqc.py
- resolwe_bio/tests/processes/test_support_processors.py
> Fix Bisulfite conversion rate related processes

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/common/README.md
- resolwe_bio/docker_images/common/packages-manual/bedtools.sh
> Bump Bedtools in resolwebio/common:1.3.2 image

- docs/CHANGELOG.rst
- resolwe_bio/processes/support_processors/merge_samples.py
> Fix handling .fastq.gz extensions in merge-fastq processes

- docs/CHANGELOG.rst
> Prepare release 27.0.0

- docs/CHANGELOG.rst
- resolwe_bio/processes/workflows/wgbs.yml
This PR adds Trimming to WGBS workflow. It is recommended to apply clipping of Illumina adapters and specific tails introduced in some library preparation kits for bisulfite sequencing. Prior tests show an increase from 30% mapped reads to more than 70% mapped reads which makes it a useful addition to the workflow.
commit(s).
mandatory …
> Add trimming in wgbs workflows

- docs/CHANGELOG.rst
- resolwe_bio/processes/support_processors/alignment_summary.py
> Fix data type of adapters input in alignment-summary process

- docs/CHANGELOG.rst
- resolwe_bio/descriptors/sample.yml
> Add Dictyostelium purpureum species choice to sample descriptor schema

- docs/CHANGELOG.rst
> Prepare release 28.0.0

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/rnaseq/README.md
- resolwe_bio/docker_images/rnaseq/packages-debian.txt
- resolwe_bio/docker_images/rnaseq/packages-manual/salmon.sh
Fix build issues for some R packages dependencies
commit(s). …
> Bump Salmon to 1.2.1 in resolwebio/rnaseq Docker

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/chipseq/Dockerfile
- resolwe_bio/docker_images/chipseq/README.md
- resolwe_bio/docker_images/chipseq/packages-debian-buildreq.txt
- resolwe_bio/docker_images/chipseq/packages-debian.txt
- resolwe_bio/docker_images/chipseq/packages-manual/r-packages.sh
> Add ChIPQC in resolwebio/chipseq Docker image

- resolwe_bio/processes/slamdunk/alleyoop_collapse.py
- resolwe_bio/processes/slamdunk/slamdunk.py
> Remove non-ascii characters from processes

- docs/CHANGELOG.rst
- resolwe_bio/processes/import_data/nucleotide_seq.py
> Bump memory requirements in upload-fasta-nucl process

- docs/CHANGELOG.rst
- resolwe_bio/processes/variant_calling/lofreq.yml
- resolwe_bio/tools/lofreq2_indel_ovlp.py
> Fix filtering of empty VCF files in Lofreq process

- resolwe_bio/processes/chip_seq/chipqc.py
This fixes CCplot generation in chipqc process by using updated version of docker image that includes a fix from ChipQC repository. 
commit(s).
input …
> Fix calculations for CCplot

- docs/CHANGELOG.rst
> Prepare release 29.0.0

- docs/CHANGELOG.rst
- resolwe_bio/processes/alignment/star.yml
> Add various limit options to alignment-star process

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/common/README.md
- resolwe_bio/docker_images/common/packages-debian.txt
- resolwe_bio/docker_images/common/packages-manual/sra-toolkit.sh
> Bump SRA toolkit version in resolwebio/common Docker image

- docs/CHANGELOG.rst
- resolwe_bio/processes/import_data/sra_file.py
- resolwe_bio/tests/processes/test_import.py
Requires https://github.com/genialis/resolwe-bio/pull/922
> Use SRA toolkit 2.10.0

- tests/docker-compose.yml
- tests/settings.py
Inspired by https://github.com/genialis/resolwe/pull/693.
> Use default password for database connections

- resolwe_bio/processes/import_data/sra_file.py
- resolwe_bio/tests/processes/test_import.py
> Fix platform-dependent ordering of FASTQC reports

- docs/CHANGELOG.rst
> Prepare release 30.0.0

- docs/CHANGELOG.rst
- resolwe_bio/descriptors/sample.yml
> Track Sample QC information in Sample descriptor schema

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/common/README.md
- resolwe_bio/docker_images/common/packages-manual/samtools.sh
For markdup statistics file we have to update Samtools to 1.10.
commit(s).
* …
> Bump Samtools to version 1.10 in resolwebio/common:1.6.0 Docker image

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/wgbs/Dockerfile
> Use resolwebio/common:1.6.0 for the resolwebio/wgbs:1.3.0 Docker image

- docs/CHANGELOG.rst
- resolwe_bio/processes/chip_seq/chipqc.py
If the first chromosome in the list had a low number of reads mapped to it ChIPQC would fail. This fix uses docker with updated ChIPQC to fix this.
commit(s). …
> Fix read length estimation in chipqc

- docs/CHANGELOG.rst
- resolwe_bio/processes/exome_coverage/coveragebed.yml
- resolwe_bio/processes/expression/featureCounts.yml
- resolwe_bio/processes/expression/salmon.py
- resolwe_bio/processes/support_processors/library_strandedness.yml
- resolwe_bio/processes/support_processors/qorts_qc.py
- resolwe_bio/processes/variant_calling/preprocess_bam.yml
- feature_counts
- coveragebed
- library-strandedness
- qorts-qc
- salmon-quant
- vc-realign-recalibrate
commit(s).
input parameter, use a different …
> Bump process memory requirements to 32GB where required

- resolwe_bio/processes/go_enrichment/go.yml
- resolwe_bio/tools/goea.py
> Bump Docker image version in goenrichment process

- docs/CHANGELOG.rst
- resolwe_bio/processes/workflows/slamdunk.yml
> Rename workflow-slamdunk-paired process

- resolwe_bio/processes/support_processors/multiqc.py
> Fix typo and version in multiqc process

- docs/CHANGELOG.rst
> Prepare release 31.0.0

- docs/CHANGELOG.rst
- resolwe_bio/processes/support_processors/multiqc.py
- resolwe_bio/tests/files/nanostring_lane_attr.txt
- resolwe_bio/tests/files/nanostring_qc.txt
- resolwe_bio/tests/files/nanostring_qc_2.txt
- resolwe_bio/tests/processes/test_support_processors.py
This PR adds custom table to display Nanostring Sample QC in MultiQC reports.
commit(s). …
> Add nanostring sample report table in multiqc

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/rnaseq/packages-manual/bbmap.sh
> Install BBMap from Google Drive

- docs/CHANGELOG.rst
- resolwe_bio/processes/chip_seq/rose2.py
The input ``input_upload`` is not a part of a sample.
> Attach rose2 Data object to the input sample

- docs/CHANGELOG.rst
> Prepare release 32.0.0

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/chipseq/packages-debian.txt
- resolwe_bio/docker_images/chipseq/packages-manual/r-packages.sh
XML needs to be pinned in order to build docker image with the newest ChIPQC.
commit(s). …
> Pin XML R package version in resolwebio/chipseq

- docs/CHANGELOG.rst
- resolwe_bio/processes/chip_seq/chipqc.py
Requires new resolwebio/chipseq image with updated ChIPQC.
commit(s).
* **PATCH …
> Fix enrichment heatmap plot in chipqc process

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/sra-toolkit/packages-manual/sra-toolkit.sh
- resolwe_bio/docker_images/sra-tools/Dockerfile
- resolwe_bio/docker_images/sra-tools/README.md
- resolwe_bio/docker_images/sra-tools/packages-debian.txt
- resolwe_bio/docker_images/sra-tools/packages-manual.txt
- resolwe_bio/docker_images/sra-tools/packages-manual/fastqc.sh
- resolwe_bio/docker_images/sra-tools/packages-manual/sra-toolkit.sh
- resolwe_bio/docker_images/sra-tools/packages-manual/trimmomatic.sh
> Add resolwebio/sra-tools Docker image

- docs/CHANGELOG.rst
- resolwe_bio/processes/import_data/sra_file.py
- resolwe_bio/tools/parse_encoding_type.py
> Use resolwebio/sra-tools Docker image in SRA import processes

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/orange/Dockerfile
- resolwe_bio/docker_images/orange/README.md
- resolwe_bio/docker_images/orange/packages-debian.txt
- resolwe_bio/docker_images/orange/packages-python3.txt
> Add resolwebio/orange Docker image

- docs/CHANGELOG.rst
- resolwe_bio/processes/import_data/sra_file.py
- resolwe_bio/tests/processes/test_import.py
> Use prefetch in SRA import processes

- docs/CHANGELOG.rst
> Prepare release 33.0.0

- resolwe_bio/tests/processes/test_upload.py
Remove part of the test related to the validate_regex
functionality. Data objects with missing or incompatible
inputs do not pass validation and are not created, thus
checking their status is not required.
commit(s). …
> Update test_upload_master_file test

- docs/CHANGELOG.rst
- resolwe_bio/processes/chip_seq/macs2.yml
> Support S. cerevisiea in macs2-callpeak process

- docs/CHANGELOG.rst
- setup.py
> Prepare release 34.0.0

- docs/CHANGELOG.rst
- resolwe_bio/processes/import_data/proteomics_data.py
- resolwe_bio/tests/files/proteomics/input/sample_set.txt
- resolwe_bio/tests/files/proteomics/input/single_sample.txt
- resolwe_bio/tests/files/proteomics/output/sample_set.txt
- resolwe_bio/tests/files/proteomics/output/single_sample.txt
- resolwe_bio/tests/processes/test_upload.py
- upload-proteomics-sample-set
- upload-proteomics-sample
commit(s).
* **PATCH …
> Add processes to upload custom tables holding proteomics data

- docs/CHANGELOG.rst
- resolwe_bio/processes/support_processors/bam_conversion.py
> Changed output from BEDPE to bigwig

- docs/CHANGELOG.rst
- resolwe_bio/processes/import_data/sra_file.py
> Bump memory requirements in SRA import processes

- docs/CHANGELOG.rst
> Prepare release 34.2.0

- docs/CHANGELOG.rst
- resolwe_bio/processes/chip_seq/macs2.yml
> Fix macs2-callpeak process version

- docs/CHANGELOG.rst
- resolwe_bio/descriptors/general_clinical.yml
> Add initial default clinical annotation schema

- resolwe_bio/descriptors/general_clinical.yml
> Fix variable type of time fields in general clinical descriptor schema

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/base/Dockerfile.ubuntu-20.04
- resolwe_bio/docker_images/base/README.md
> Add resolwebio/base:ubuntu-20.04 Docker image

- docs/CHANGELOG.rst
> Prepare release 34.3.0

- docs/CHANGELOG.rst
- resolwe_bio/descriptors/oncxerna_clinical.yml
> Add OncXerna specific descriptor schema

- resolwe_bio/processes/WGBS/walt.yml
- resolwe_bio/processes/alignment/bwa.yml
> Bump walt process storage requirements

- resolwe_bio/processes/WGBS/walt.yml
> Further bump walt process storage requirements

- docs/CHANGELOG.rst
> Prepare release 35.0.0

- resolwe_bio/processes/slamdunk/slamdunk.py
> Bump storage requirement for slamdunk-all-paired process

- docs/CHANGELOG.rst
- setup.py
> Prepare release 36.0.0

- docs/CHANGELOG.rst
- resolwe_bio/processes/import_data/seq_reads_multiplexed.yml
> Fix file import in demultiplex processes

- docs/CHANGELOG.rst
- resolwe_bio/processes/chip_seq/macs2_batch.yml
- resolwe_bio/processes/chip_seq/macs2_rose2_batch.yml
- resolwe_bio/processes/expression/merge_etc.yml
- resolwe_bio/processes/import_data/cuffquant.yml
- resolwe_bio/processes/import_data/geneset.yml
- resolwe_bio/processes/import_data/mappability_tab.yml
- resolwe_bio/processes/import_data/metadata.py
- resolwe_bio/processes/import_data/sam_header.yml
- resolwe_bio/processes/import_data/snpeff.yml
- resolwe_bio/processes/import_data/sra_file.py
- resolwe_bio/processes/import_data/target_pcr_metrics.yml
- resolwe_bio/processes/support_processors/prepare_geo.yml
- resolwe_bio/processes/unit_tests/test_basic_fields.yml
- resolwe_bio/processes/unit_tests/test_disabled_fields.yml
- resolwe_bio/processes/unit_tests/test_hidden_fields.yml
- resolwe_bio/processes/unit_tests/test_list.yml
- resolwe_bio/processes/unit_tests/test_sleep_progress.yml
- resolwe_bio/tests/processes/test_chipseq.py
- resolwe_bio/tests/processes/test_diff_expression.py
- resolwe_bio/tests/processes/test_slamdunk.py
- resolwe_bio/tests/processes/test_support_processors.py
- resolwe_bio/tests/processes/test_wgbs.py
> Only use tagged versions of base Docker images

- docs/CHANGELOG.rst
> Prepare release 36.1.0

- docs/CHANGELOG.rst
- resolwe_bio/processes/support_processors/multiqc.py
- resolwe_bio/tests/processes/test_support_processors.py
> Fix handling of non-sample data inputs in multiqc process

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/sra-tools/Dockerfile
- resolwe_bio/docker_images/sra-tools/README.md
- resolwe_bio/docker_images/sra-tools/packages-debian-buildreq.txt
- resolwe_bio/docker_images/sra-tools/packages-debian.txt
- resolwe_bio/docker_images/sra-tools/packages-python3.txt
> Add dnaio in resolwebio/sra-tools Docker image

- docs/CHANGELOG.rst
- resolwe_bio/processes/import_data/sra_file.py
> Add fastq file validation in SRA import processes

- docs/CHANGELOG.rst
> Prepare release 38.0.0

- docs/CHANGELOG.rst
- resolwe_bio/tests/processes/test_microarray.py
Cleanup commit of a test.
commit(s). …
> Drop duplicated code in test_probe_mapping

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/dnaseq/Dockerfile
- resolwe_bio/docker_images/dnaseq/README.md
- resolwe_bio/docker_images/dnaseq/packages-debian-buildreq.txt
- resolwe_bio/docker_images/dnaseq/packages-debian.txt
- resolwe_bio/docker_images/dnaseq/packages-manual/gatk.sh
> Bump GATK version in resolwebio/dnaseq image

- docs/CHANGELOG.rst
- tests/settings.py
> Cap process memory consumption at 16GB

- docs/CHANGELOG.rst
- pyproject.toml
- setup.py
- tox.ini
> Add support for Python 3.9, upgrade setuptools

- docs/CHANGELOG.rst
- resolwe_bio/kb/management/commands/insert_features.py
- resolwe_bio/kb/management/commands/insert_mappings.py
> Support downloading kb features and mappings from S3

- docs/CHANGELOG.rst
- resolwe_bio/processes/variant_calling/genotype_gvcfs.py
- resolwe_bio/processes/variant_calling/vqsr.py
Process unit test was not implemented due to the need for large input files holding the training/truth variant sets.
> Add VQSR variant filtering process

- docs/CHANGELOG.rst
- resolwe_bio/kb/listener_plugin.py
- resolwe_bio/processes/microarray/methylation_arrays.py
- resolwe_bio/tests/files/large/methylation_beta_values_annotated.txt.gz
- resolwe_bio/tests/files/methylation/inputs/illumina_probe_ids_to_ensembl.tab
- resolwe_bio/tests/files/methylation/output/QC_data.txt
- resolwe_bio/tests/processes/test_microarray.py
- resolwe_bio/tools/sesame.R
This PR adds a sesame process for analyzing methylation arrays. It includes a Python process with R code that does the actual heavy lifting.
commit(s). …
> SeSAMe implemented for methylation array pipeline

- resolwe_bio/processes/variant_calling/vqsr.py
> Fix advanced options input path in gatk-vqsr

- docs/CHANGELOG.rst
> Prepare release 31.1.0

- docs/CHANGELOG.rst
> Prepare release 38.1.1

- docs/CHANGELOG.rst
- resolwe_bio/processes/variant_calling/wgs_preprocess.py
> Fix stalled processing in wgs-preprocess

- docs/CHANGELOG.rst
- resolwe_bio/processes/reads_processing/bam_to_fastq.py
> Parallelize BAM to FASTQ file format conversion

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/methylation_arrays/Dockerfile
- resolwe_bio/processes/microarray/methylation_arrays.py
This PR makes the `methylation_arrays` Docker image work in offline mode.
commit(s). …
> Make Bioconductor config file available offline

- docs/CHANGELOG.rst
- resolwe_bio/processes/reads_processing/bbduk.yml
> Add qin and ignorebadquality options to BBDuk single/paired process

- docs/CHANGELOG.rst
> Prepare release 38.3.0

- docs/CHANGELOG.rst
- resolwe_bio/processes/variant_calling/wgs_preprocess.py
- resolwe_bio/processes/workflows/wgs_gvcf.py
- resolwe_bio/tests/workflows/test_wgs.py
- Revert CPU/memory settings for WGS pre-processing step
- make trimmomatic step optional in the WGS workflow
> WGS pipeline updates

- resolwe_bio/processes/variant_calling/wgs_preprocess.py
- Set Data name correctly for BAM inputs
- Increase storage requirements
- Set TPMDIR location in GATK tools
commit(s). …
> Fix wgs-preprocess tool

- resolwe_bio/processes/variant_calling/wgs_preprocess.py
> Set TMPDIR for MarkDuplicates in wgs-preprocess

- docs/CHANGELOG.rst
> Prepare release 38.4.0

- docs/CHANGELOG.rst
- resolwe_bio/processes/support_processors/merge_samples.py
- resolwe_bio/tests/processes/test_support_processors.py
> Update FASTQ file merging to use sample relations

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/dnaseq/packages-debian-buildreq.txt
- resolwe_bio/docker_images/dnaseq/packages-manual.txt
- resolwe_bio/docker_images/dnaseq/packages-manual/ensembl-vep.sh
- resolwe_bio/docker_images/dnaseq/packages-manual/perl-packages.sh
* [x ] Update CHANGELOG.rst for each commit separately:
commit(s).
* **PATCH …
> Add ensembl-vep to the resolwebio/dnaseq:6.2.0 Docker image

- resolwe_bio/processes/variant_calling/gatk_variant_refinement.py
commit(s).
* [x ] Bump the process version: …
> Fix process type and delete entity in GATK genotype refinement process

- docs/CHANGELOG.rst
> Prepare release 39.0.0

- docs/CHANGELOG.rst
> Prepare release 40.0.0

- resolwe_bio/processes/import_data/seq_reads.py
> Remove info in processes Upload FASTQ and Files to FASTQ

- docs/CHANGELOG.rst
- resolwe_bio/processes/variant_calling/ensembl_vep.py
> Add fork parameter in ensembl-vep

- docs/CHANGELOG.rst
> Prepare release 41.0.0

- docs/CHANGELOG.rst
> Prepare release 42.0.0

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/dnaseq/Dockerfile
- resolwe_bio/docker_images/dnaseq/README.md
- resolwe_bio/docker_images/dnaseq/packages-debian-buildreq.txt
- resolwe_bio/docker_images/dnaseq/packages-debian.txt
- resolwe_bio/docker_images/dnaseq/packages-manual/gatk.sh
- resolwe_bio/docker_images/dnaseq/packages-manual/r-packages.sh
- resolwe_bio/docker_images/dnaseq/packages-r.txt
Pin R package versions 
Bump GATK version to 4.2.4.1
> Pin R package versions and bump GATK version in resolwebio/dnaseq:6.3.0 Docker image

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/dnaseq/packages-manual/ensembl-vep.sh
> Fix Ensembl-VEP installation in resolwebio/dnaseq Docker image

- docs/CHANGELOG.rst
- resolwe_bio/processes/reads_processing/bqsr.py
- resolwe_bio/tests/files/bqsr/output/TP53.primerclipped.markduplicates.bam_stats.txt
- resolwe_bio/tests/processes/test_reads_filtering.py
> Add parameter --use-original-qualities to BQSR process

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/common/assets/multiqc_config.yml
> Update MultiQC config file in common Docker image

- docs/CHANGELOG.rst
- resolwe_bio/processes/support_processors/multiqc.py
- resolwe_bio/tests/processes/test_support_processors.py
- Bump Docker image to include the updated MultiQC configuration file
- Fix handling of --cl-config input option
commit(s). …
> Use updated config file in MultiQC process

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/snpeff/Dockerfile
- resolwe_bio/docker_images/snpeff/README.md
- resolwe_bio/docker_images/snpeff/packages-manual/snpeff.sh
> Update SnpEff version to 5.1 in resolwebio/snpeff Docker image

- docs/CHANGELOG.rst
- resolwe_bio/docker_images/snpeff/Dockerfile
- resolwe_bio/docker_images/snpeff/README.md
- resolwe_bio/docker_images/snpeff/packages-debian.txt
> Add tool Tabix to resolwebio/snpeff Docker image

- docs/CHANGELOG.rst
> Prepare release 44.0.0

- docs/CHANGELOG.rst
- resolwe_bio/processes/reads_processing/bqsr.py
- resolwe_bio/processes/reads_processing/markduplicates.py
- resolwe_bio/processes/reads_processing/split_ncigar.py
- resolwe_bio/processes/support_processors/alignment_summary.py
- resolwe_bio/processes/support_processors/insert_size.py
- resolwe_bio/processes/support_processors/rrbs_metrics.py
- resolwe_bio/processes/support_processors/wgs_metrics.py
- resolwe_bio/processes/variant_calling/gatk4.py
- resolwe_bio/processes/variant_calling/gatk4_hc.py
- resolwe_bio/processes/variant_calling/gatk_merge_vcfs.py
- resolwe_bio/processes/variant_calling/gatk_select_variants.py
- resolwe_bio/processes/variant_calling/gatk_variant_filtration.py
- resolwe_bio/processes/variant_calling/gatk_variant_refinement.py
- resolwe_bio/processes/variant_calling/genotype_gvcfs.py
- resolwe_bio/processes/variant_calling/variants_to_table.py
- resolwe_bio/processes/variant_calling/vqsr.py
> Specify TMP dir for GATK processes

- docs/CHANGELOG.rst
- resolwe_bio/processes/clustering/find_similar.py
- resolwe_bio/processes/clustering/hierarchical_clustering_etc.py
> Set Persistance to TEMP in processes find-similar and clustering-hierarchical-etc

- docs/CHANGELOG.rst
- resolwe_bio/processes/workflows/amplicon.yml
- resolwe_bio/processes/workflows/atac_seq.yml
- resolwe_bio/processes/workflows/bbduk_salmon_qc.py
- resolwe_bio/processes/workflows/bbduk_star_featurecounts_qc.py
- resolwe_bio/processes/workflows/chip_seq.yml
- resolwe_bio/processes/workflows/corall.yml
- resolwe_bio/processes/workflows/cuffquant.yml
- resolwe_bio/processes/workflows/cut_and_run.yml
- resolwe_bio/processes/workflows/mirna.yml
- resolwe_bio/processes/workflows/quantseq.py
- resolwe_bio/processes/workflows/shrna.yml
- resolwe_bio/processes/workflows/slamdunk.yml
- resolwe_bio/processes/workflows/wes.yml
- resolwe_bio/processes/workflows/wgbs.yml
- resolwe_bio/processes/workflows/wgs.yml
> Attach worfklow Data objects to Samples

- resolwe_bio/processes/support_processors/mutations_table.py
- resolwe_bio/tests/processes/test_support_processors.py
> Add check for presence of reference variants in process Mutations table

- resolwe_bio/processes/import_data/ml_ready_expressions.py
- resolwe_bio/processes/import_data/ml_ready_reference.py
Fixes:
-  decided to add dropdown's for species and source, since it is error prone to type them manually (found out that during testing)
- Also, fix a minor bug by casting integer list to string list
> Small fixes for reference-space and upload-ml-expression processes

- docs/CHANGELOG.rst
> Prepare release 44.1.0

- docs/CHANGELOG.rst
- resolwe_bio/migrations/0004_merge_fastq_type.py
- resolwe_bio/processes/support_processors/merge_samples.py
> Update merge FASTQ process type

- docs/CHANGELOG.rst
- resolwe_bio/processes/variant_calling/filtering_chemut.py
- resolwe_bio/processes/workflows/chemut.yml
- resolwe_bio/tests/files/chemut/output/variant_filtered.txt
- resolwe_bio/tests/processes/test_variant_calling.py
> Fix variants_filtered output in Variant filtering (CheMut)

- docs/CHANGELOG.rst
- resolwe_bio/processes/microarray/methylation_arrays.py
> Use resolwebio/methylation_arrays:1.1.0 in methylation-array-sesame

- docs/CHANGELOG.rst
- setup.py
> Require Resolwe 31.x

- docs/CHANGELOG.rst
> Prepare release 47.0.0

- docs/CHANGELOG.rst
> Prepare release 47.1.0

- docs/CHANGELOG.rst
- resolwe_bio/processes/workflows/bbduk_salmon_qc.py
- resolwe_bio/tests/workflows/test_rna_seq.py
> Add options to calculate variance of counts in Salmon RNA-seq workflow

- docs/CHANGELOG.rst
- resolwe_bio/processes/reads_processing/rnaseq_vc_preprocess.py
> Bump memory requirements for RNA-seq variant calling preprocess

- docs/CHANGELOG.rst
- resolwe_bio/descriptors/dicty_time_series.yml
> Add dicty-time-series descriptor schema

- docs/CHANGELOG.rst
> Prepare release 47.2.0

- docs/CHANGELOG.rst
- resolwe_bio/descriptors/unified-descriptor.yml
> Flatten General descriptor schema

- docs/CHANGELOG.rst
> Prepare release 47.3.0

- docs/CHANGELOG.rst
- resolwe_bio/descriptors/unified-descriptor.yml
> Rename group general_information to general in general DS

- docs/CHANGELOG.rst
- resolwe_bio/descriptors/unified-descriptor.yml
> Change separators in field names in General descriptor schema

- docs/CHANGELOG.rst
- resolwe_bio/descriptors/unified-descriptor.yml
…escriptor schema
commit(s).
* **PATCH version (last number)**: changes/bug fixes …
> Change label values of the field biomarkers_pdl1_tps_cat in General descriptor schema

- docs/CHANGELOG.rst
- resolwe_bio/kb/views.py
> Enable ordering on knowledge-base endpoints

- docs/CHANGELOG.rst
- resolwe_bio/processes/variant_calling/gatk4_hc.py
> Add option for interval padding to GATK HaplotypeCaller

- docs/CHANGELOG.rst
- resolwe_bio/processes/reads_processing/rnaseq_vc_preprocess.py
> Add memory limit to RNA-seq variant calling preprocess

- docs/CHANGELOG.rst
- resolwe_bio/__about__.py
> Prepare release 49.0.0

- .readthedocs.yml
> Bump Python version to 3.10 in readthedocs config

- docs/CHANGELOG.rst
- resolwe_bio/processes/alignment/star_index_new.py
- resolwe_bio/processes/alignment/star_new.py
- resolwe_bio/tests/files/test_star/output/hs_paired_stats_beta.txt
- resolwe_bio/tests/files/test_star/output/hs_single_stats_beta.txt
- resolwe_bio/tests/files/test_star/output/paired_lanes_stats_beta.txt
- resolwe_bio/tests/files/test_star/output/single_lanes_stats_beta.txt
- resolwe_bio/tests/processes/test_alignment.py
NOTE: STAR aligner beta can only use genome index computed with STAR genome index beta processes, since the latest STAR aligner version does not support the use of STAR index computed with our original STAR genome index process.
commit(s).
* **MINOR version (middle number)**: add functionality …
> Add processes STAR and STAR genome index with 2.7.10b STAR version

- docs/CHANGELOG.rst
- docs/conf.py
- setup.py
- tests/settings.py
> Require resolwe 33.x

- resolwe_bio/processes/workflows/bbduk_star.py
- resolwe_bio/processes/workflows/bbduk_star_new.py
- resolwe_bio/tests/workflows/test_rna_seq.py
> Add cDNA index to QoRTs inputs in STAR-based RNA-seq workflow

- docs/CHANGELOG.rst
> Prepare release 50.0.0

- docs/CHANGELOG.rst
- resolwe_bio/processes/clustering/find_similar.py
- resolwe_bio/processes/clustering/hierarchical_clustering.py
- resolwe_bio/processes/clustering/hierarchical_clustering_etc.py
- resolwe_bio/processes/clustering/pca.yml
- resolwe_bio/processes/go_enrichment/go.py
- resolwe_bio/processes/import_data/geneset.py
- resolwe_bio/processes/support_processors/archive.yml
- setup.py
> Optimize resource usage for interactive processes

- docs/CHANGELOG.rst
- resolwe_bio/processes/workflows/bbduk_star.py
- resolwe_bio/tests/workflows/test_rna_seq.py
> Add option for 2-pass mode to BBDuk-STAR workflow

- docs/CHANGELOG.rst
- resolwe_bio/processes/expression/star_quantification.py
- resolwe_bio/tests/processes/test_expression.py
> Add output field feature_type to STAR quantification process

- docs/CHANGELOG.rst
> Prepare release 51.0.0

- docs/CHANGELOG.rst
- resolwe_bio/processes/WGBS/walt.yml
- resolwe_bio/processes/alignment/bowtie.yml
- resolwe_bio/processes/alignment/bowtie2_index.py
- resolwe_bio/processes/alignment/bowtie_index.py
- resolwe_bio/processes/alignment/bwa.yml
- resolwe_bio/processes/alignment/hisat2.yml
- resolwe_bio/processes/alignment/hisat2_index.py
- resolwe_bio/processes/alignment/star.py
- resolwe_bio/processes/chip_seq/chipqc.py
- resolwe_bio/processes/chip_seq/prepeak_qc.yml
- resolwe_bio/processes/expression/cufflinks.yml
- resolwe_bio/processes/expression/cuffquant.yml
- resolwe_bio/processes/expression/salmon.py
- resolwe_bio/processes/microarray/methylation_arrays.py
- resolwe_bio/processes/reads_processing/alignmentsieve.py
- resolwe_bio/processes/reads_processing/bbduk.py
- resolwe_bio/processes/reads_processing/cutadapt.yml
- resolwe_bio/processes/reads_processing/cutadapt_3prime.py
- resolwe_bio/processes/reads_processing/cutadapt_corall.py
- resolwe_bio/processes/reads_processing/trimgalore.py
- resolwe_bio/processes/reads_processing/trimmomatic.yml
- resolwe_bio/processes/scseq/cellranger.py
- resolwe_bio/processes/support_processors/library_strandedness.yml
> Adjust process resource settings

- docs/CHANGELOG.rst
- resolwe_bio/processes/workflows/rnaseq_variant_calling.py
> Fix BBDuk settings in RNA-seq VC workflow

- docs/CHANGELOG.rst
- setup.py
- tests/settings.py
> Always use Docker default seccomp profile

- docs/CHANGELOG.rst
> Prepare release 52.0.0

- docs/CHANGELOG.rst
- resolwe_bio/kb/listener_plugin.py
- resolwe_bio/process/models.py
and use Redis to cache them
EXP-611
> Add listener command to query Feature objects

- docs/CHANGELOG.rst
- resolwe_bio/processes/alignment/bowtie.yml
> Set process resources in Bowtie aligners

- docs/CHANGELOG.rst
- resolwe_bio/processes/workflows/geo_import.py
> Improve GEO import warnings for missing raw data

- docs/CHANGELOG.rst
- resolwe_bio/processes/workflows/rnaseq_variant_calling.py
- resolwe_bio/tests/workflows/test_rna_seq.py
> Support optional triggering of MultiQC of RNA-seq VC workflow and rename the workflow

- docs/CHANGELOG.rst
> Prepare release 53.0.0

- docs/CHANGELOG.rst
- resolwe_bio/processes/alignment/bwa.yml
> Bump storage requirements in BWA processes

- docs/CHANGELOG.rst
> Prepare release 53.1.0

- docs/CHANGELOG.rst
- resolwe_bio/processes/support_processors/multiqc.py
for all samples in MultiQC
commit(s). …
> Report gene coverage and assigned reads

- docs/CHANGELOG.rst
- setup.py
> Prepare release 53.2.0

- docs/CHANGELOG.rst
- resolwe_bio/expression_filters/sample.py
- resolwe_bio/tests/unit/test_expression_filters.py
> Add sample_annotation jinja expressions filter

- docs/CHANGELOG.rst
- resolwe_bio/processes/alignment/star.py
- resolwe_bio/processes/workflows/geo_import.py
- resolwe_bio/tests/processes/test_alignment.py
- resolwe_bio/tests/workflows/test_geo_import.py
- resolwe_bio/utils/test.py
- setup.py
> Update processes using annotations

- docs/CHANGELOG.rst
> Prepare release 54.0.0

- Jenkinsfile
- docs/CHANGELOG.rst
- setup.py
- tox.ini
> Use Python 3.11 for tests

- docs/CHANGELOG.rst
> Prepare release 55.0.0

- docs/CHANGELOG.rst
- resolwe_bio/processes/workflows/bbduk_star.py
- resolwe_bio/processes/workflows/bbduk_star_featurecounts_qc.py
> Use downsampled alignment for RNA-SeQC in workflows

- resolwe_bio/processes/samtools/samtools_bedcov.py
> Change the process type of ``samtools-bedcov``

- docs/CHANGELOG.rst
> Prepare release 55.1.0

- docs/CHANGELOG.rst
- resolwe_bio/processes/chip_seq/macs2.py
- resolwe_bio/processes/chip_seq/macs2_batch.yml
- resolwe_bio/processes/chip_seq/prepeak_qc.yml
This PR rewords some of the processes (related to MACS2) to point out that it can be used to analyze data from other methods, such as CUT&RUN, as well.
commit(s). …
> Reword MACS2 documentation

- docs/CHANGELOG.rst
> Prepare release 52.2.0

- docs/CHANGELOG.rst
- resolwe_bio/processes/support_processors/multiqc.py
> Fix MultiQC with MACS2 in broad peak mode

- .github/workflows/ci.yml
> Add simple github actions workflow

- docs/CHANGELOG.rst
- resolwe_bio/processes/support_processors/multiqc.py
> Fix handling downsampled STAR inputs in MultiQC

- docs/CHANGELOG.rst
- resolwe_bio/processes/samtools/samtools_depth.py
> Fix handling of large files in ``samtools-depth`` process

- .github/workflows/ci.yml
- tests/compose.yaml
> Upgrade PostgreSQL used in tests to version 16

- .github/workflows/ci.yml
- docs/CHANGELOG.rst
- docs/contributing.rst
> Build (pre)release automatically on tag push

- docs/CHANGELOG.rst
> Prepare release 56.0.0

- docs/CHANGELOG.rst
- setup.py
> Require Resolwe 40.x

- .github/workflows/mypy.yml
since it fails and marks entire job as failed
commit(s).
* **PATCH version (last …
> Do not run type checks on every pull request

- docs/CHANGELOG.rst
- resolwe_bio/processes/clustering/pca.py
> Add changes to ``pca-beta`` process

- docs/CHANGELOG.rst
> Prepare release 58.0.0

- docs/CHANGELOG.rst
- resolwe_bio/processes/workflows/geo_import.py
> Add retries for SRA query in geo-import process

- .github/workflows/ci.yml
- docs/CHANGELOG.rst
- setup.py
- tox.ini
> Use partial testing

- resolwe_bio/kb/listener_plugin.py
> Change iteration size in listener for kb models to 10000

- docs/CHANGELOG.rst
- resolwe_bio/processes/alignment/star.py
- resolwe_bio/processes/workflows/bbduk_star.py
[REID-2400](https://genialis.atlassian.net/browse/REID-2400)
commit(s).
* **PATCH …
> Modify star.py and bbduk_star.py for fusion calling

- docs/CHANGELOG.rst
- resolwe_bio/process/models.py
- resolwe_bio/process/runtime.py
- resolwe_bio/variants/listener_plugin.py
- resolwe_bio/variants/tests/test_process.py
- resolwe_bio/variants/tests/test_variant.py
> Expose variant objects in python processes

- resolwe_bio/processes/workflows/bbduk_star.py
> Bump ``workflow-bbduk-star-qc`` workflow version

- docs/CHANGELOG.rst
In this PR, many processes have been removed, warranting a major version change.
> Prepare release 59.0.0

- docs/CHANGELOG.rst
- resolwe_bio/variants/filters.py
- resolwe_bio/variants/tests/test_variant.py
> Add filters by sample to variant objects

- resolwe_bio/processes/fusion_calling/arriba.py
The function was failing since contig names could include integer, whereas `" ".join()` method expects all elements in the list to be strings. This has now been fixed. Additionally, `pd.read_csv()` function was updated to ignore commented lines, as some .gtf files include metadata in such manner.
commit(s).
mandatory input, removing …
> Fix get_contig_names() fuction

- resolwe_bio/processes/samtools/samtools_mpileup.py
> Make changes to ``samtools-mpileup``

- resolwe_bio/processes/fusion_calling/arriba.py
- resolwe_bio/tests/processes/test_arriba.py
> Beautify arriba.py and test_arriba.py scripts

- docs/CHANGELOG.rst
- resolwe_bio/processes/alignment/star.py
> Fix star.py to correctly handle --chimOutType parameters

- docs/CHANGELOG.rst
> Prepare release 59.1.0

- resolwe_bio/processes/annotation/variant_annotation.py
* [] Update CHANGELOG.rst for each commit separately:
commit(s). …
> Replace nan with empty string

- docs/CHANGELOG.rst
- resolwe_bio/processes/import_data/seq_reads.py
- resolwe_bio/processes/reads_processing/bbduk.py
> Optimize resource usage in BBDuk and FASTQ read import processes

- docs/CHANGELOG.rst
- resolwe_bio/processes/workflows/gene-fusion-calling-arriba.py
> Fix rendering of star_index input field in gene-fusion-calling-arriba workflow

- docs/CHANGELOG.rst
- resolwe_bio/processes/fusion_calling/arriba.py
> Bump arriba resource requirements

- docs/CHANGELOG.rst
> Prepare release 60.0.0

- docs/CHANGELOG.rst
- resolwe_bio/variants/filters.py
- resolwe_bio/variants/tests/test_variant.py
> Return only distinct VariantExperiment objects

- docs/CHANGELOG.rst
> Prepare release 61.1.0

- docs/CHANGELOG.rst
> Prepare release 61.2.0

- .github/workflows/ci.yml
- .github/workflows/mypy.yml
> Use public docker runner in CI workflow

- .github/workflows/ci.yml
- docs/CHANGELOG.rst
- pyproject.toml
- tox.ini
> Add support for Python 3.13

- docs/CHANGELOG.rst
- resolwe_bio/variants/models.py
- resolwe_bio/variants/serializers.py
- resolwe_bio/variants/tests/test_variant.py
- resolwe_bio/variants/views.py
> Create variants, variantcall and variantexperiment objects via API

- tests/settings.py
since the VersionField has been moved to Resolwe .
commit(s). …
> Remove the versionfield app

- .github/workflows/ci.yml
- docs/CHANGELOG.rst
> Prepare release 62.0.0

- docs/CHANGELOG.rst
- pyproject.toml
> Require Resolwe 44.x

- docs/CHANGELOG.rst
- resolwe_bio/process/runtime.py
> Send variants from processes in batches

- docs/CHANGELOG.rst
- resolwe_bio/processes/support_processors/multiqc.py
> Fix genebody coverage plot in MultiQC

- docs/CHANGELOG.rst
> Prepare release 63.0.0

- docs/CHANGELOG.rst
> Prepare release 63.1.0

- docs/CHANGELOG.rst
- pyproject.toml
and bump requirements version to sync with Resolwe.
commit(s). …
> Require Resolwe 45.x

- README.rst
- docs/contributing.rst
- docs/descriptor.rst
- docs/proc.rst
> Update docs and readme
