genialis/resolwe-bio

resolwe_bio/tools/utils.py

Redis would fail for spawn processes with unicode dict keys.

Changed mongo keys from unicode to str

---

tests/settings.py

In addition to RESOLWE_POSTGRESQL_PORT, a developer can now set:
- RESOLWE_POSTGRESQL_NAME,
- RESOLWE_POSTGRESQL_USER,
- RESOLWE_POSTGRESQL_HOST.
This makes Resolwe Bioinformatics follow [Resolwe's test settings](https://github.com/genialis/resolwe/blob/fe0a0135f7c8e6ad76410f1668839823b407f1d9/tests/settings.py#L70).

Allow setting PostgreSQL settings via environment variables in tests

---

docs/CHANGELOG.rst
tox.ini

Add `--process-dependency-links` to Tox's pip install command to ensure a developer can easily bump a dependency to the latest git version while developing on a personal feature branch.
Make command that pulls Docker images aware of the `RESOLWE_EXECUTOR_COMMAND` environment variable.
Change the wildcard to pass all environment variables starting with `RESOLWE_` or `RESOLWEBIO_` to Tox's testing environment.

Make Tox configuration more robust to different developer environments

---

tests/docker-compose.yml
tests/settings.py

Change default PostgreSQL port to 55433 to avoid a collision with
Resolwe's default PostgreSQL port. If a developer wants to use
docker-compose with each project's default configuration, this is now
possible since the projects' docker-compose settings don't interfere
anymore.

Change default PostgreSQL port to avoid a collision with Resolwe

---

tests/settings.py

Change destination directory to /data_all since it must not be under
/home/biolinux as the latter has the owner and group recursively
changed to match the host user's and that cannot work with read-only
volumes.
**TODO**:

Change the destination of the DATA_PATH Docker mapping

---

resolwe_bio/kb/serializers.py

After upgrading `django-rest-framework`, tests are failing with:
AssertionError: (u"Creating a ModelSerializer without either the 'fields' attribute or the 'exclude' attribute has been deprecated since 3.3.0, and is now disallowed. Add an explicit fields = '__all__' to the FeatureSearchSerializer serializer.",)

Fix kb serializer

---

resolwe_bio/expression_filters/sample.py
resolwe_bio/management/commands/generate_diffexpr_cuffdiff.py
resolwe_bio/management/commands/generate_diffexpr_deseq.py
resolwe_bio/tools/build_gene_info_hsapiens.py
resolwe_bio/tools/build_gene_info_mus.py
resolwe_bio/tools/demultiplex.py
resolwe_bio/tools/expression2storage.py
resolwe_bio/tools/gff3_to_gtf.py
resolwe_bio/tools/go_genesets.py
resolwe_bio/tools/importETC.py
resolwe_bio/tools/summarize_expression_ncRNA.py
resolwe_bio/tools/xexpression.py
resolwe_bio/tools/xgtf2gff.py
setup.cfg
setup.py

Tests are failing with:
************* Module resolwe_bio.kb.models
C: 63, 4: Old-style class defined. (old-style-class)
************* Module resolwe_bio.kb.serializers
C: 18, 4: Old-style class defined. (old-style-class)
@tjanez, @kostko do you have any idea why? Exact same definition for Meta class is passing on Resolwe. Is it possible that linters are run on python 2.7 here and on 3.5 on Resolwe (classes with no parent specified are old-style objects in py2 and new-style objects in py3)?

Update pycodestyle config

---

setup.py

This works around problems when running `python setup.py install --force` and incorrect versions of Django and Django REST Framework dependencies are installed.
This should fix the Read the Docs builds.

Manually specify Django and Django REST Framework dependencies

---

.gitignore
MANIFEST.in
docs/CHANGELOG.rst
tests/.env
tests/docker-compose.yml

By default, project name equals the directory name, where `docker-compose.yml` resides.
Since directory name is `tests`, this is prone to clashes with other projects, so we manually set it to `resolwebio`.

Set Docker Compose's project name to 'resolwebio' to avoid name clashes

---

README.rst
docs/contributing.rst
setup.py

When installing from source or preparing a contributor development environment, use `--process-dependency-links` pip argument to be able to install the latest `master` version of Resolwe from git.
Specify an exact version of Resolwe (during development phase of Resolwe Bioinformatics) and change it to `master` so that it will be always installed from git.

Document when '--process-dependency-links' has to be used

---

docs/CHANGELOG.rst
tests/settings.py

Change test project's settings to allow setting a custom command for the
Docker executor via 'RESOLWE_DOCKER_COMMAND' environment variable.

Use Resolwe's new 'FLOW_DOCKER_COMMAND' setting in test project

---

setup.py

Sphinx version 1.6 doesn't work with our custom page template.

Temporarily pin Sphinx to version 1.5.x

---

resolwe_bio/processes/workflows/rnaseq.yml

When selecting rnaseq workflow in Bioinformatics Dashboard / Tool Catalog, the unquoted default values _yes_ and _no_ make the corresponding input fields display incorrectly on the front-end. The tests run correctly in both versions of the workflow.

Fix quotation marks in rnaseq workflow

---

resolwe_bio/processes/go_enrichment/go.yml
resolwe_bio/processes/icount/annotation.yml
resolwe_bio/processes/icount/genome.yml
resolwe_bio/processes/variant_calling/snpeff.yml

Requires genialis/resolwe#293
Note that these are the minimal limits to make the process unit tests pass. In practice some additional resources may be required for other processes or existing resources need to be changed.

Set correct resource limits based on tests

---

docs/CHANGELOG.rst
resolwe_bio/processes/import_data/sra_file.yml

The new inputs enable fine-tuning the import process. The immediate use case is to specify _Maximum spot ID_ to limit the number of downloaded reads and thus speed up the process.
In the future a parallel fastq-dump (see [here](https://github.com/rvalieris/parallel-fastq-dump)) can be used to reduce the download time (not implemented yet).

Add new inputs to import SRA process

---

docs/CHANGELOG.rst
resolwe_bio/processes/clustering/hierarchical_clustering.yml
resolwe_bio/processes/clustering/pca.yml
resolwe_bio/tests/processes/test_clustering.py
resolwe_bio/tests/processes/test_pca.py

Hidden state was not set for `genes_source` input because it did not react to the changes in the content of the `genes` input.

Fix gene source check in hierarchical clustering and PCA

---

.gitattributes

This reverts commit 4463434a9a3441868caa2395351eedf6fce46a51.
We had many issues with wrongly "merged" CHANGELOGs and people often didn't notice them. Hence, it is better to present developers with the conflicted regions and ask them to manually resolve the them.

Revert "Use git's 'union' merge driver for the CHANGELOG"

---

docs/CHANGELOG.rst
resolwe_bio/__about__.py

I've noted backward incompatible changes in the CHANGELOG.

Prepare release 3.0.0 and bump version to 3.1.0a1

---

tests/settings.py

We've recently changed the resolwe 'register' command to
also pull Docker images after process registration is done,
as this prevents using stale or obsolete Docker images in
tests, as well as in production.
In some cases, this might not be desired, so a new setting
was added to prevent pulling images.  This can be useful
during development, since the developer will probably not
want to pull all the images on every test run.
To use this option, simply set the environment variable
'RESOLWE_DOCKER_DONT_PULL' to '1'.

Add 'FLOW_DOCKER_DONT_PULL' setting

---

docs/CHANGELOG.rst
resolwe_bio/tests/workflows/test_rna_seq.py
resolwe_bio/utils/test.py

Remove `BioProcessTestCase` that enclosed tests' code in a transaction and rename the non-transactional `TransactionBioProcessTestCase` to `BioProcessTestCase`.

Make BioProcessTestCase non-transactional

---

docs/CHANGELOG.rst
docs/contributing.rst
setup.cfg
setup.py
tox.ini

Use `python_requires` `setup()` argument to specify the required Python version.

Drop Python 2 support, require Python 3.4 or 3.5

---

docs/CHANGELOG.rst
resolwe_bio/processes/reads_processing/bbduk.yml

Internal estimation of free RAM by 'bbduk' sometimes returns a negative value if the memory requirement is not explicitly specified.

Set maximum RAM requirement in 'bbduk' process

---

docs/CHANGELOG.rst
resolwe_bio/tests/processes/test_enrichment.py
resolwe_bio/utils/test.py

Requires genialis/resolwe#220.
@jkokosar, could you take a look why the `test_go_enrichment` test returns different values for `pval` and `score` which cause the test to fail?
Here is the diff:
```
$ diff obtained-result.json result-from-file.json 
75,76c75,76
<                                                 "pval": 0.5333333333333332,
<                                                 "score": 0.75,
---
>                                                 "pval": 0.6666666666666671,
>                                                 "score": 1.5,
86,87c86,87
<                                         "pval": 0.5333333333333332,
<                                         "score": 0.75,
---
>                                         "pval": 0.6666666666666671,
> …
```

Make tests use the live Resolwe API host instead of external server

---

resolwe_bio/tests/processes/test_alignment.py
resolwe_bio/tests/processes/test_demultiplex.py
resolwe_bio/tests/processes/test_support_processors.py
resolwe_bio/tests/workflows/test_amplicon.py
resolwe_bio/tests/workflows/test_chemut.py
resolwe_bio/tests/workflows/test_chip_seq.py
resolwe_bio/tests/workflows/test_heat_seq.py
resolwe_bio/tests/workflows/test_rna_seq.py
resolwe_bio/tests/workflows/test_wgbs.py
setup.py

Fix wrong order of imports in tests.
The upgrade to Pylint 1.8.0+ is necessary to fix the current `master` branch test failures of type:
```
linters runtests: commands[2] | pylint resolwe_bio .scripts/check_large_files.py
************* Module resolwe_bio.utils.test
W: 72, 0: Unused variable '__class__' (unused-variable)
W: 72, 0: Unused variable '__class__' (unused-variable)
W: 72, 0: Unused variable '__class__' (unused-variable)
W: 72, 0: Unused variable '__class__' (unused-variable)
W: 72, 0: Unused variable '__class__' (unused-variable)
W: 72, 0: Unused variable '__class__' (unused-variable)
W: 72, 0: Unused variable '__class__' (unused-variable)
W: 72, 0: Unused variable '__class__' (unused-variable)
W: 72, 0: Unused variable '__class__' (unused-variable)
W:136, 0: Unused variable …
```

Use Pylint 1.8.0+

---

docs/CHANGELOG.rst
resolwe_bio/docker_images/base/Dockerfile.ubuntu-17.10
resolwe_bio/docker_images/base/README.md
resolwe_bio/docker_images/dnaseq/Dockerfile
resolwe_bio/docker_images/dnaseq/README.md
resolwe_bio/docker_images/rnaseq/Dockerfile
resolwe_bio/docker_images/rnaseq/README.md
resolwe_bio/processes/import_data/pathway_map.yml

Ubuntu 17.04 reached end of life on 13. 1. 2018, so it is removed from
base images and Ubuntu 17.10 is added instead.

Switch Docker base image from Ubuntu 17.04 to Ubuntu 17.10

---

docs/CHANGELOG.rst
resolwe_bio/docker_images/rnaseq/Dockerfile
resolwe_bio/docker_images/rnaseq/README.md

After transition to the `resolwebio/base` Docker image Bioconductor packages stopped working. This is fixed by installing system Ubuntu packages of the affected Bioconductor libraries.

Change base Docker image of resolwebio/rnaseq to resolwebio/base:ubuntu-18.04

---

docs/CHANGELOG.rst
resolwe_bio/docker_images/rnaseq/packages-debian-buildreq.txt
resolwe_bio/docker_images/rnaseq/packages-manual/trimmomatic.sh

Fix passing parameters from the custom script forward to the `Trimmomatic` tool. The `$@` in the custom script were not escaped and didn't survive the script creation process. 
In this PR two custom scripts are created (one for single and one for paired-end reads) to mimic the `trimmomatic` system package in Ubuntu. This allows calling `Trimmomatic` in the same manner as [before](https://github.com/genialis/resolwe-bio/blob/master/resolwe_bio/processes/import_data/seq_reads.yml#L68).

Fix custom Trimmomatic script in resolwebio/rnaseq Docker image

---

docs/CHANGELOG.rst
resolwe_bio/processes/support_processors/bam_split.yml
resolwe_bio/tests/processes/test_support_processors.py

@jkokosar 
@mstajdohar  Either this process or sample tagging for hybrid builds must be changed so we decided to change this process because this new formatting is better. This should be deployed with the next redeploy and should have high priority.

Change expected genome build formatting for hybrid genomes in bam-split

---

docs/CHANGELOG.rst
resolwe_bio/docker_images/dnaseq/Dockerfile
resolwe_bio/docker_images/dnaseq/README.md
resolwe_bio/docker_images/dnaseq/packages-manual/samtools.sh

@jkokosar 
This is necessary because I can't reinstall anything in the (now unsupported) Ubuntu 17.04 image, and Rsamtools doesn't install properly in the 17.10 image.

Update dnaseq Docker image base to Ubuntu 18.04

---

docs/CHANGELOG.rst
resolwe_bio/processes/expression/featureCounts.yml
resolwe_bio/processes/workflows/mirna.yml

Fixed some typos and synced description of input parameter common to `miRNA` workflow and `featureCounts` process. Please review @mzganec @jkokosar @JenkoB @JureZmrzlikar.

Fix typos and sync parameter descriptions in miRNA and featureCounts

---

tests/settings.py

Django Channels only allow unicode strings containing only ASCII alphanumerics, hypens or periods for a Channel name.
This will fix Jenkins failure like [this](https://ci.genialis.com/job/genialis-github/job/resolwe-bio/job/stable%252F7.0.x/1/).

Ensure Manager channel prefix is valid in test project's settings

---

docs/CHANGELOG.rst
resolwe_bio/processes/expression/htseq_count.yml

Name ordering is used to prevent buffer overflow with large BAM files.

Use name-ordered BAM file in HTSeq-count process by default

---

docs/CHANGELOG.rst
resolwe_bio/docker_images/base/common.sh

The original `download_and_verify()` script handles dotted filenames incorrectly, e.g. https://cdn.pydata.org/bokeh/release/bokeh-0.12.13.min.css is named `assets.12.13.min.css` when downloaded in https://github.com/genialis/resolwe-bio/pull/523. The case where `name` [contains a space](https://github.com/genialis/resolwe-bio/blob/master/resolwe_bio/docker_images/base/common.sh#L44) is also fixed.

Improve manual installation of packages in Docker images

---

docs/CHANGELOG.rst
resolwe_bio/docker_images/chipseq/packages-manual/bedgraphtobigwig.sh
resolwe_bio/docker_images/chipseq/packages-manual/bedtobigbed.sh
resolwe_bio/docker_images/chipseq/packages-manual/wigtobigwig.sh

Pull bedGraphToBigWig, bedToBigBed and wigToBigWig from Drive. On the official website version is updated very frequently and the link remains the same (pointing the latest version), but hash is changing.
@JureZmrzlikar @kostko please review

Pull USCS tools from Google Drive

---

docs/CHANGELOG.rst
resolwe_bio/processes/alignment/bowtie.yml
resolwe_bio/processes/alignment/bwa.yml
resolwe_bio/processes/alignment/hisat2.yml
resolwe_bio/processes/alignment/star.yml
resolwe_bio/processes/alignment/subread.yml
resolwe_bio/processes/alignment/tophat.yml
resolwe_bio/tools/bamtobigwig.sh

Fix bamtobigwig calculation to timeout after defined time

---

docs/CHANGELOG.rst
resolwe_bio/processes/workflows/bbduk_star_featurecounts.yml

Remove duplicated forward of alignIntronMax input field in
BBDuk - STAR - featureCounts workflow.
commit(s).
input parameter, use a different tool …

Remove duplicated input forward in RNA-seq workflow

---

docs/CHANGELOG.rst
resolwe_bio/processes/import_data/annotation.yml

Fix upload-gtf to covert GTF to GFF for JBrowse track

---

docs/CHANGELOG.rst
resolwe_bio/processes/import_data/annotation.yml

Fix upload-gtf to create JBrowse track only when GTF is ok

---

resolwe_bio/processes/chip_seq/macs2.yml

When tagalign file is used for MACS2 analysis, the `*_control_lambda.bdg` can contain overlapping features. This does not conform with the bedgraph file format specifications and consequently, the conversion to BigWig format fails. To solve the issue `bedtools merge` is used with options `-d -1` (merge features that overlap with at least 1 bp) and `-c 4 -o mean` (for merged regions, the value in column 4 is averaged) before the conversion to BigWig format.

Fix MACS2 bigwig creation for overlapping features in control lambda bedgraph file

---

resolwe_bio/processes/support_processors/spikeins_qc.yml
resolwe_bio/tests/processes/test_support_processors.py
resolwe_bio/tools/spikein_pairwise.py

This fixes the error that appeared if sample name contained dots.
The presence of dots in sample name (and absence of format
parameter in savefig method) caused matplotlib to autmatically
determine format. It took the part of sample name that is following
the last dot as a file extension.

Explicitly set image format in spikein_pairwise.py tool

---

docs/CHANGELOG.rst
resolwe_bio/docker_images/rnaseq/README.md
resolwe_bio/docker_images/rnaseq/packages-manual/r-packages.sh

An R package has been developed in order to serve the functionality of the short hairpin RNA differential expression process. This PR puts this package into `rnaseq` image. I think the docker image should be tagged as 4.4.0.

Add shRNAde R package to rnaseq docker image

---

docs/CHANGELOG.rst
resolwe_bio/processes/import_data/annotation_bedpe.py
resolwe_bio/processes/reads_processing/bqsr.py
resolwe_bio/processes/workflows/wes.yml
resolwe_bio/tests/processes/test_reads_filtering.py
resolwe_bio/tests/workflows/test_wes.py

This PR adds a dropdown menu to `upload-bedpe` process. Selection of species name can now be done like for any other process.
Because some bam files are not structured the way certain tools want them, a validation stringency parameter has been introduced into all subprocesses called within the `bqsr` process.
commit(s).
mandatory input, …

Fix WES bam validation issues

---

docs/CHANGELOG.rst
resolwe_bio/processes/reads_processing/markduplicates.py

Because I forgot to bump version of `markduplicates` process the pipeline was failing when I added another value (`LENIENT`) to parameter of `validation_stringency`. This is now also documented in the changelog.
commit(s). …

Bump version in markduplicates process

---

docs/CHANGELOG.rst
resolwe_bio/processes/reads_processing/bamclipper.py
resolwe_bio/processes/workflows/wes.yml
resolwe_bio/tests/processes/test_reads_filtering.py
resolwe_bio/tests/workflows/test_wes.py

This PR adds a skip parameter to `bamclipper` tool. This enables the WES pipeline to process not only data from amplicon based kits, but also hybridization based kits.
commit(s).
backwards-compatible manner. Examples: add …

Add skip parameter to bamclipper process and wes-pipeline workflow

---

resolwe_bio/processes/reads_processing/cutadapt_3prime.py
resolwe_bio/processes/reads_processing/cutadapt_corall.py

The use of Plumbum's BG command modifier causes IO input stream errors when incomplete output files were passed to FASTQC process downstream of Cutadapt. I have reverted to the default use of Plumbum, with the downside of cutadapt_report.txt file now holding stdout info for just the last of the multiple calls to Cutadapt.

Remove BG command  modifier in Cutadapt processes

---

docs/CHANGELOG.rst
resolwe_bio/processes/import_data/annotation_bedpe.py

This pull request grants access to network for process `upload-bedpe` to enable uploading of files from the internet.
commit(s).
input parameter, use …

Add network access to upload-bedpe process

---

README.rst

- Status icon in README is updated to work with the two-step authentication on the new Jenkins server.
- When the build status is clicked, link points to the new Blue Ocean interface instead of the old Jenkins interface.

Update build status icon

---

docs/CHANGELOG.rst
resolwe_bio/processes/reads_processing/bamclipper.py
resolwe_bio/processes/reads_processing/bqsr.py
resolwe_bio/processes/reads_processing/markduplicates.py
setup.py

Cases, where bigwig file was not calculated, stopped. This PR makes the output field of bigwig not required and should solve this problem.
Sphinx is having problems parsing docstrings so we're freezing the docutils to version 0.15.2.
commit(s). …

Make bigwig field not mandatory for bamclipper, bqsr and markduplicates

---

docs/CHANGELOG.rst
setup.py

Sphinx has problems parsing the dev version of `docutils` (0.16b.0). For the time being, we are freezing the version to 0.15.2.
commit(s).
input …

Explain why docutils has been frozen to 0.15.2

---

docs/CHANGELOG.rst
resolwe_bio/processes/alignment/star.yml
resolwe_bio/tests/processes/test_alignment.py

Star samtools sort

---

docs/CHANGELOG.rst
resolwe_bio/processes/differential_expression/shRNAde.py
resolwe_bio/processes/import_data/bam_scseq.py
resolwe_bio/processes/import_data/seq_reads_10x.py
resolwe_bio/processes/reads_processing/bamclipper.py
resolwe_bio/processes/reads_processing/bqsr.py
resolwe_bio/processes/reads_processing/cutadapt_3prime.py
resolwe_bio/processes/reads_processing/cutadapt_corall.py
resolwe_bio/processes/reads_processing/markduplicates.py
resolwe_bio/processes/scseq/cellranger.py

Noticed a typo that has been disseminated through a few processes possibly due to copy/pasting.
commit(s).
input parameter, use a different tool that …

Fix typo in scheduling_class parameter in several Python processes

---

docs/CHANGELOG.rst
resolwe_bio/processes/reads_processing/bqsr.py
resolwe_bio/tests/processes/test_reads_filtering.py

A user might have incorrectly specify tag of the `read_group` argument. This PR checks that all inputs have the `-XX` structure.
Checks now goes from broad to specific, i.e. first it makes sure all tags exist/are correctly entered, there are no duplicates and finally if mandatory tags are used.
commit(s).
mandatory input, removing …

Handle improper read_group tags in bqsr process

---

docs/CHANGELOG.rst
resolwe_bio/kb/tests/test_mapping.py
resolwe_bio/kb/views.py

If one did a Mappings query with multiple source_id/target_id as
query parameter the response would be empty or Error. There are
multiple options for one to get multiple Mappings from api. These
are the actual query parameters in request URL:
1. source_id="ID1,ID2"
2. source_id=["ID1", "ID2"]
3. source_id__in="ID1,ID2"
4. source_id__in=["ID1", "ID2"]
The main point is that value of query parameter must be casted to
list as some point. Since source_id is a custom filter the "__in"
snytax is not allowed (3. and 4. are not an option) but there is
no place in code where 1. and 2. would be casted to list. Therefore
the result of 1. or 2 was empty and 3. or 4. raised error.
This solution removes source_id (and targed_id) as custom filters
and places them as normal filtering parameters. …

Fix Mapping search for source_id / target_id

---

.gitignore
.readthedocs.yml
MANIFEST.in

Solves the issue with Read the Docs documentation failing. During the documentation build, instead of specified pyasn1 package, pyasn1-modules is selected instead. As a consequence, pyasn1 package is missing.
We switch to [Read the Docs configuration file](https://docs.readthedocs.io/en/stable/config-file/v2.html) to work around this issue.

Add Read the Docs configuration file

---

Jenkinsfile

Current timeout in Jenkinsfile is set to 60 minutes, which is too short and many processes get killed. Timeout is increased to 90 minutes.

Increase jenkins timeout to 90 minutes

---

tox.ini

When tests are run, most of the steps are skipped, because tox does not support spaces in environment definitions.
Changes:
- Change definition for basepython builds in tox.ini

Fix tox testenv

---

docs/CHANGELOG.rst
resolwe_bio/processes/chip_seq/macs14.yml
resolwe_bio/processes/chip_seq/macs2.yml
resolwe_bio/processes/junctions/regtools.yml
resolwe_bio/tools/bed_file_corrections_genome_browsers.py

For some samples, the MACS analysis fails to identify peaks and thus produces an empty .narrowpeaks file. In such cases, Pandas `EmptyDataError` occurs. With this fix, we can detect such events and fail the process with a more user-friendly error message.

Handle empty input in BED file correction script

---

docs/CHANGELOG.rst
resolwe_bio/processes/support_processors/alignment_summary.py
resolwe_bio/tests/processes/test_support_processors.py

This commit fixes handling of multiple adapter sequences in alignment-summary process.
commit(s).
input parameter, use a different tool that produces …

Fix handling of multiple adapters in alignment-summary process

---

resolwe_bio/processes/support_processors/multiqc.py

Fix symlink for enrichment heatmap as it was set on a wrong data output.
commit(s). …

Fix enrichment heatmap symlink in multiqc

---

docs/CHANGELOG.rst
resolwe_bio/processes/alignment/bowtie.yml
resolwe_bio/tests/files/test_bowtie2/output/bowtie2_no_overlap_report.txt
resolwe_bio/tests/files/test_bowtie2/output/bowtie2_no_unal_report.txt
resolwe_bio/tests/processes/test_alignment.py

This PR adds parameters `--no-unal`, `--no-overlap` and `--dovetail` parameters to bowtie2 process.
Latter parameter pertains only to paired-end reads, which is why it's added only to that part of the code.
commit(s). …

Add parameters --no-unal, --no-overlap and --dovetail to bowtie2 process

---

docs/CHANGELOG.rst
resolwe_bio/tools/bamtobigwig.sh

Two added parameters are `--normalizeUsing` and `--smoothLength` to be used in the bamCoverage program.
Since there's no explicit test for this process, I tried running all tests that I could find that check for `.bw` file (test_bwa, test_hisat2_bigwig...). They don't seem to produce any errors.
commit(s).
mandatory input, removing …

Add two extra parameters to bamtobigwig.sh script

---

docs/CHANGELOG.rst
resolwe_bio/docker_images/rnaseq/README.md
resolwe_bio/docker_images/rnaseq/packages-manual.txt
resolwe_bio/docker_images/rnaseq/packages-manual/trimgalore.sh

Trim galore will be used in cut&run pipeline. It is added to rnaseq docker as it requires Cutadapt and Fastqc.
commit(s). …

Add Trim galore in resolwebio/rnaseq:4.12.0

---

docs/CHANGELOG.rst
resolwe_bio/processes/WGBS/walt.yml
resolwe_bio/processes/alignment/bowtie.yml
resolwe_bio/processes/alignment/bwa.yml
resolwe_bio/processes/alignment/hisat2.yml
resolwe_bio/processes/alignment/star.yml

Previously, when one wanted to align the same reads to two or more different species, an error was issued and process stopped. Here we relax this and make it a warning.
commit(s).
backwards-compatible manner. Examples: add …

Alignment processes issue a warning on genome-read species mismatch

---

docs/CHANGELOG.rst
resolwe_bio/processes/alignment/bowtie.yml
resolwe_bio/processes/reads_processing/alignmentsieve.py
resolwe_bio/processes/reads_processing/markduplicates.py
resolwe_bio/processes/workflows/cut_and_run.yml
resolwe_bio/tests/processes/test_alignment.py
resolwe_bio/tests/processes/test_reads_filtering.py
resolwe_bio/tests/workflows/test_cut_and_run.py

Primary reason for this PR is the addition of timeout parameter to `workflow-cutnrun` and corresponding processes. Due to the way the `bamtobigwig.sh` script is written, it makes sense to also add bin size.
commit(s). …

Add BigWig timeout and bin size parameters

---

docs/CHANGELOG.rst
resolwe_bio/kb/serializers.py
resolwe_bio/kb/tests/test_feature.py
resolwe_bio/kb/tests/test_mapping.py

Motivation for this PR: fix the issue with iterate() in ReSDK, that relies on object's id. But until now, filtering by id was not possible for features / mappings.

Add id field to Feature and Mapping serializers

---

docs/CHANGELOG.rst
resolwe_bio/processes/import_data/metadata.py

Template in update-orange-template needs to be updated to include mS#Sample, ms#Sample name, mS#Sample ID and mS#Sample slug. The template is now located on our google drive and can be changed if needed.
commit(s). …

Update template table in upload-orange-metadata

---

docs/CHANGELOG.rst
resolwe_bio/processes/import_data/sra_file.py
resolwe_bio/tests/processes/test_import.py

This fixes recoding of Illumina 1.5 and 1.3 encoding. Encoding is determined by parsing FASTQC output file using `parse_encoding_type.py` tool which prints the encoding to stdout. By default newline is added at the end of the print statement. 
commit(s). …

Fix quality recoding in SRA import processes

---

docs/CHANGELOG.rst
resolwe_bio/processes/microarray/methylation_arrays.py
resolwe_bio/tests/files/large/methylation_beta_values_annotated.txt.gz
resolwe_bio/tools/sesame.R

Ensembl ID mapping of probes has been removed for now.
In addition, probe chromosome position, stand/end of CpG and
strand have been added to the output of the SeSAMe pipeline.
commit(s).
backwards-compatible manner. …

Remove Ensembl IDs and add extra variables to SeSAMe output

---

docs/CHANGELOG.rst
resolwe_bio/processes/microarray/methylation_arrays.py
resolwe_bio/tests/files/large/methylation_beta_values_annotated.txt.gz
resolwe_bio/tools/sesame.R

Two things are changed in this ~bugfix:
* docstring now documents that start and end position are 1- based
* betas column was removed from output by accident on the last refactoring and is now returned
commit(s). …

Return betas and improve docstrings for methylation-array-sesame pipeline

---

docs/CHANGELOG.rst
resolwe_bio/tools/create_gene_sets.py

Gene set upload could fail if unsafe characters were used. Here we implement the [approach](https://github.com/django/django/blob/795051b2b04020866fc14c858b77972ef8e5a3e2/django/utils/text.py#L225) used in Django to create clean file names.
commit(s). …

Use clean file name for gene sets in create_gene_sets.py

---

docs/CHANGELOG.rst
resolwe_bio/processes/variant_calling/variants_to_table.py

* [ x] Update CHANGELOG.rst for each commit separately:
commit(s).
* [ x] Bump the process version:
input parameter, use a different tool that …

Fix data name and advanced options in GATK VariantsToTable process

---

docs/CHANGELOG.rst
resolwe_bio/processes/variant_calling/genotype_gvcfs.py
tests/settings.py

Allocating more memory to Java speeds up the analyisis. Additionaly this removes the two unused parameters.
commit(s). …

Add java memory setting in gatk-genotype-gvcfs

---

docs/CHANGELOG.rst
resolwe_bio/processes/differential_expression/deseq.py
resolwe_bio/tests/processes/test_diff_expression.py
resolwe_bio/tools/deseq.R

Previously if `independent` field was set to `False` nothing changed and the independent filtering was applied regardless. This PR aims to fix this and retain the old behaviour of using filtering by default (also default in DESeq2).
commit(s). …

Set independent field to True in DESeq2 process

---

resolwe_bio/processes/alignment/star.py

Fix automatic species annotation in STAR

---

resolwe_bio/processes/import_data/expressions.py

Fix supported extensions in descriptions for Upload expression process

---

resolwe_bio/processes/variant_calling/gatk_select_variants.py

Fix ref_seq parameter in gatk-select-variants

---

docs/CHANGELOG.rst
resolwe_bio/processes/variant_calling/ensembl_vep.py
resolwe_bio/tests/processes/test_variant_calling.py

Change Ensembl-VEP version check in Ensembl-VEP process

---

docs/CHANGELOG.rst
resolwe_bio/processes/differential_expression/deseq.py
resolwe_bio/tests/processes/test_diff_expression.py

Build field was not accessed correctly since upgrading to a new protocol. This fixes it and adds a test to avoid this in future.
commit(s).
input …

Fix build mismatch error in DESeq2

---

docs/CHANGELOG.rst
resolwe_bio/processes/expression/featureCounts.py

featureCounts class is renamed to FeatureClass to be PEP compliant.
Calling the progress (bar) is now fixed.
commit(s). …

Rename featureCounts class and fix progress reporting

---

resolwe_bio/processes/variant_calling/wgs_preprocess_bwa2.py

Indexing would fail because the intervals were not passed to the ApplyBQSR.
commit(s). …

Fix scattering in wgs-preprocess-bwa2

---

resolwe_bio/processes/go_enrichment/go.py

Fix output handling in GO Enrichment Analysis process

---

.scripts/check_large_files.py
resolwe_bio/processes/import_data/seq_reads.py
resolwe_bio/processes/import_data/sra_file.py
resolwe_bio/processes/workflows/bbduk_star_featurecounts_qc.py
resolwe_bio/tools/spikein_pairwise.py

Fix disabled option for Chimeric reads options in General RNA-seq pipeline

---

docs/CHANGELOG.rst
resolwe_bio/processes/reads_processing/bqsr.py
resolwe_bio/processes/reads_processing/markduplicates.py
resolwe_bio/processes/reads_processing/split_ncigar.py
resolwe_bio/tests/processes/test_reads_filtering.py

Add Java memory setting to processes MarkDuplicates, BQSR and GATK SplitNCigarReads

---

docs/CHANGELOG.rst
tests/settings.py

Fix LISTENER_CONNECTION settings

---

docs/CHANGELOG.rst
resolwe_bio/processes/support_processors/merge_samples.py
resolwe_bio/tests/processes/test_support_processors.py

This PR should improve error messages for the wrong type of relations or inputs without them. However, this process can still produce unexpected results. For example, a user could select the wrong type of relations and also have all replicate relations defined, which would merge based on replicate relations and not the selected type. The latest push adds a warning for multiple relations defined on a data object.
commit(s).
* **MAJOR version (first number)**: Backward incompatible …

Fix handling missing relations in merge-sample processes

---

docs/CHANGELOG.rst
resolwe_bio/processes/import_data/metadata.py

Requires `public.ecr.aws/s4q6j6e8/resolwebio/common:3.1.0` which replaces Orange Docker image (BIOINF-74).
commit(s).
input parameter, use a different …

Use resolwebio/common Docker image for metadata upload

---

docs/CHANGELOG.rst
resolwe_bio/processes/chip_seq/macs2.py

This PR removes piped Plumbum commands to improve stability of the `macs2-callpeak` process.
commit(s).
input parameter, use a different tool that …

Fix sporadically failing macs2 tests

---

docs/CHANGELOG.rst
resolwe_bio/processes/chip_seq/macs2.py
resolwe_bio/tests/processes/test_chipseq.py

Fix fragment length and memory issues in macs2-callpeak

---

resolwe_bio/processes/reads_processing/xengsort.py

The process had insufficient memory for creating a typical index with two fasta files for host and graft organisms. 
commit(s). …

Bump memory requirements in xengsort-index

---

docs/CHANGELOG.rst
resolwe_bio/processes/chip_seq/macs2.py
resolwe_bio/processes/support_processors/multiqc.py
resolwe_bio/processes/workflows/geo_import.py
resolwe_bio/tests/processes/test_chipseq.py
resolwe_bio/tests/processes/test_support_processors.py

- Consider all three fragment length estimates to save compute resources and minimise errors in MACS2
- Use only the estimates where `estimate > 0` as expected by MACS2
- Avoid using sample names for storing ChIPQC plots in the MultiQC process to avoid missing plots in the report. This was a consequence of file name cleaning (removal of some suffixes) which led to duplicated plot ids.
commit(s).
that break the …

Fixes for the ChIP-seq pipeline

---

docs/CHANGELOG.rst
resolwe_bio/processes/reads_processing/rnaseq_vc_preprocess.py
resolwe_bio/processes/workflows/rnaseq_variant_calling.py
resolwe_bio/processes/workflows/rnaseq_variant_calling_beta.py
resolwe_bio/tests/workflows/test_rna_seq.py

This PR:
- reverts ``workflow-rnaseq-variantcalling`` to previous version with no preprocess step, while removing intervals as an input to BQSR
- adds ``workflow-rnaseq-variantcalling-beta`` which uses the preprocess step
- removes memory limits for parallel SplitNCigarReads step in RNA-seq VC preprocess

Revert RNA-seq VC workflow to previous version

---

docs/CHANGELOG.rst
resolwe_bio/processes/support_processors/multiqc.py
resolwe_bio/tests/processes/test_support_processors.py

This attempts to fix the sample name cleaning bug in MultiQC related to [BUG-817](https://genialis.atlassian.net/browse/BUG-817).
General Statistics before:
General Statistics after:
There is an additional row for each pair file/lane/etc.
commit(s). …

Fix sample naming in the MultiQC report

---

resolwe_bio/processes/support_processors/multiqc.py

In a recent MultiQC fix we moved QoRTs files to the sample directory to report those statistics in the same row as others. This fix does the same for salmon outputs. 
The outputs used to be a separate category:
commit(s). …

Symlink individual Salmon outputs in the MultiQC process

---

docs/CHANGELOG.rst
resolwe_bio/descriptors/unified-descriptor.yml

Remove group nesting for QC fields in General descriptor schema

---

docs/CHANGELOG.rst
resolwe_bio/processes/variant_calling/snpeff.py
resolwe_bio/tests/processes/test_variant_calling.py

Fix the check for genome builds of inputs in process snpEff

---

docs/CHANGELOG.rst
resolwe_bio/processes/import_data/sra_file.py

SRA processed would not allow setting minimum read length to 0. Paired-end files with 0-length reads would have those filtered out and FASTQ validation would raise an error.
commit(s).
backwards-compatible manner. Examples: …

Fix SRA import to accept 0 as minimum read length

---

docs/CHANGELOG.rst
resolwe_bio/processes/reads_processing/bbduk.py

This prevents the process from raising an error out when there are more lanes than available cores. 
commit(s).
input parameter, use a different tool …

Prevent BBduk from stopping when lanes exceed cores

---

docs/CHANGELOG.rst
resolwe_bio/processes/workflows/geo_import.py

Fix SRA parameters to pass zero values in geo-import

---

docs/CHANGELOG.rst
resolwe_bio/processes/expression/star_quantification.py
resolwe_bio/processes/support_processors/multiqc.py
resolwe_bio/processes/workflows/bbduk_star.py
resolwe_bio/tests/files/test_star/output/exp_summary.txt
resolwe_bio/tests/processes/test_support_processors.py

Report assigned reads count by STAR quantification

---

resolwe_bio/processes/workflows/geo_import.py
resolwe_bio/tests/workflows/test_geo_import.py

Fix experimental model annotation in geo-import

---

docs/CHANGELOG.rst
pyproject.toml
resolwe_bio/processes/workflows/cut_and_run_beta.py
resolwe_bio/tests/workflows/test_cut_and_run.py

Fix input fields for ``workflow-cutnrun-beta``

---

docs/CHANGELOG.rst
resolwe_bio/processes/samtools/samtools_bedcov.py

Add input option to exclude flags in ``samtools-bedcov``

---

docs/CHANGELOG.rst

Prepare release 55.3.0

---

docs/CHANGELOG.rst
resolwe_bio/processes/support_processors/multiqc.py

[REID-2289]
commit(s).
* **PATCH version (last number)**: changes/bug fixes that …

Add gene body coverage information to MultiQC

---

docs/CHANGELOG.rst
resolwe_bio/processes/import_data/sra_file.py

REID-2233
commit(s).
* **PATCH version (last number)**: changes/bug fixes that do …

Add retry for reads prefetch in ``import-sra``

---

docs/CHANGELOG.rst

Prepare release 54.4.0

---

docs/CHANGELOG.rst
resolwe_bio/processes/workflows/geo_import.py
resolwe_bio/tests/workflows/test_geo_import.py

in ``geo-import`` process
REID-2336
commit(s). …

Remove sample annotation functionality  from ``geo-import`` process

---

docs/CHANGELOG.rst
resolwe_bio/processes/support_processors/multiqc.py
resolwe_bio/tests/processes/test_support_processors.py

This fixes cases of overwritten STAR aligner reports when parsing data by MultiQC. When the same (or similar) inputs are given, the solution is to store the reports in separate folders. This produces additional lines in General stats table

Fix handling of multiple instances of STAR aligner input in the MultiQC process

---

docs/CHANGELOG.rst
resolwe_bio/processes/reads_processing/xengsort.py

Come hell or high water, ensure that the number of threads is always an integer.
commit(s). …

Fix coercing the number of threads to int in the ``xengsort-index`` process

---

resolwe_bio/tests/workflows/test_geo_import.py

This is a temporary measure as the web resource is experiencing technical difficulties, making end-to-end test unusable.

Skip GEO import tests

---

resolwe_bio/processes/alignment/star.py
resolwe_bio/processes/workflows/bbduk_star.py

This PR fixes the incorrectly typed `WithinBam` parameter (correctly typed is `WithinBAM` and adds two more explicit options for soft/hard clipping.
If only `WithinBAM` is used, `WithinBAM HardClip` is assumed and the `WithinBAM SoftClip` option was added for greater flexibility.
commit(s).
* …

Fix and add more choices to --chimOutType parameter in STAR

---

docs/CHANGELOG.rst
resolwe_bio/processes/support_processors/bam_conversion.py

Fix --numberOfProcessors in calculate-bigwig

---

resolwe_bio/processes/support_processors/gtf_to_bed.py

Add additional outputs to "gtf-to-bed"

---

docs/CHANGELOG.rst
resolwe_bio/processes/alignment/star.py
resolwe_bio/processes/workflows/bbduk_star.py

This PR changes the default value of the `--chimOutType` STAR parameter to `WithinBAM HardClip` since the `SeparateSAMold`is (to be) deprecated.
commit(s). …

Change default values of --chimOutType STAR parameter

---

docs/CHANGELOG.rst

Prepare release 59.2.0

---

docs/CHANGELOG.rst
setup.py

Require Resolwe 41.x

---

docs/CHANGELOG.rst
resolwe_bio/processes/import_data/geneset.py
resolwe_bio/variants/filters.py
resolwe_bio/variants/tests/test_variant.py
setup.cfg

Allow filtering variant experiment by sample

---

.github/workflows/ci.yml

Use Github OIDC as a Trusted publisher on Pypi

---

docs/CHANGELOG.rst
resolwe_bio/__about__.py

Make source distribution filenames compliant with PEP 625

---

setup.py

Prevents installing prereleases when no `--pre` flag is given to pip install. Pull request changes this behavior:
```
$ cat requirements-pre.txt 
resolwe>=42.0a1, ==42.*
$ pip install -r requirements-pre.txt
$ pip freeze | grep -i resolwe                                                                                                                                                                        
resolwe==42.1.0a3
```
to this behavior:
```
$ cat requirements-stable.txt                                                                                                                                                                                                 
resolwe==42.*
$ pip install -r requirements-stable.txt
$ pip freeze | grep -i resolwe …
```

Do not force pre-release versions of resolwe

---

docs/CHANGELOG.rst
resolwe_bio/processes/support_processors/gtf_to_bed.py
resolwe_bio/tests/processes/test_support_processors.py

Make changes to ``gtf-to-bed`` process

---

docs/CHANGELOG.rst
resolwe_bio/processes/annotation/variant_annotation.py

to handle a larger number of variants
commit(s).
* **PATCH version (last …

Optimize ``variant-annotation`` process

---

docs/CHANGELOG.rst
resolwe_bio/processes/variant_calling/gatk4_hc.py

in ``vc-gatk4-hc``
commit(s).
* **PATCH version (last number)**: changes/bug fixes …

Fix the disabling of BAM writer input
